### ISSUE TITLE
Analysis for mouse (mm10) data

### ISSUE THREAD

**Issue by ShuangHe33** [saeyslab/nichenetr#1]
Thank you for your great package and manuals.
I wonder when I apply it to the mouse data, should I download the network source of mouse and reconstruct the model or can I just transfer the gene name from human to mouse.
Thank you in advance!

**Comment by browaeysrobin** [comment]
Thank you for the remark. In theory, you could collect mouse-specific data sources and reconstruct the NicheNet model, but I recommend converting the gene symbols from human to mouse. I included new functions and a vignette showing how you can do this conversion quickly: https://github.com/saeyslab/nichenetr/blob/master/vignettes/symbol_conversion.md.
