### ISSUE TITLE
get_expressed_genes function do not look for SCT assay

### ISSUE THREAD

**Issue by saeedfc** [saeyslab/nichenetr#10]
Hi,

Thank you for this amazing tool.
For those who follows SCTransform workflow with seurat (without integration) SCT assay with scale.data slot is the go to slot for DEG analysis and visualization of gene expression. In this workflow the scale.data slot for  RNA assay will be empty. I think ideally this function should also look for scaled.data slot in SCT assay as well (unless it is not suitable because of some reason that I am ignorant about).
There is a caveat though,
In this workflow, the scale.data for SCT assay will only have limited number genes (default = 3000) if scaling is not applied to all genes during seurat workflow(which is the default setting). But 'SCTransform' function allows scaling to be done with all genes if explicitly mentioned (this is  enabled in the development branch of seurat, not very sure about the cran version).

Again, Thank you!
Kind regards,
Saeed

**Comment by browaeysrobin** [comment]
Hi @saeedfc 

Thank you for pointing this out. The get_expressed_genes function will now check whether there exists an SCT slot. Expressed genes will also be defined by looking at the normalized data (data slot) and not the scaled data (scale.data slot), to avoid problems with having only 3000 genes in the scaled data slot.
Let me know whether it works now or not.

Best,
Robin
