### ISSUE TITLE
Running log-fold change of ligands from sender cells DEG issue: Error in WhichCells.Seurat(object = object, idents = ident.2) :    Cannot find the following identities in the object

### ISSUE THREAD

**Issue by ksaunders73** [saeyslab/nichenetr#100]
Hello!

I am following the https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md tutorial, and everything has worked so far except for step 6. 

When running this line (I added "celltype" as a column in the metadata to get rid of the "`Cannot find 'celltype' in this Seurat object`" error) I get that one of my variables is unable to be found:

```
DE_table_all = Idents(sobj) %>% levels() %>% intersect(sender_celltypes) %>% lapply(get_lfc_celltype, seurat_obj = sobj, condition_colname = "BC.Subtype", condition_oi = condition_oi, condition_reference = condition_reference, expression_pct = 0.10) %>% reduce(full_join)

Error in WhichCells.Seurat(object = object, idents = ident.2) : 
  Cannot find the following identities in the object: HER2+
```

But I know it's in there:

![image](https://user-images.githubusercontent.com/62159599/130366006-33a82e93-813b-448d-83ad-0203027a5d63.png)

and though I am using an integrated Seurat object, I set the default assay to RNA.

Hopefully this makes sense, and thanks for reading!

**Comment by browaeysrobin** [comment]
Hi @ksaunders73 

Could you check the following:

- What is the output of `Idents(sobj) %>% levels() %>% intersect(sender_celltypes)`?
- Are there sender_celltypes (output here above) that are not present in the HER2+ condition? if not, the Seurat DE analysis of this cell type wont work because you don't have cells for both conditions for that cell type.

**Comment by browaeysrobin** [comment]
Hi @ksaunders73 
Are you still having this issue?

**Comment by KforKuma** [comment]
I am facing a similar issue when the condition_oi I gave could not recognized by 'WhichCells.Seurat(object = object, idents = ident.1) '. I have checked my seuratobj@meta.data to make sure the celltype as well as the column itself exist. The code that met an error is like:
> nichenet_output = nichenet_seuratobj_aggregate(
nd_target_matrix = ligand_target_matrix,
  lr_network = lr_network,
  weighted_networks = weighted_networks,
  organism = "human")
+   seurat_obj = seuratobj,
+   receiver = c("cell1","cell2"),
+   condition_colname = "condition",
+   condition_oi = "condition1",
+   condition_reference = "condition2",
+   sender = sender_celltypes,
+   ligand_target_matrix = ligand_target_matrix,
+   lr_network = lr_network,
+   weighted_networks = weighted_networks,
+   organism = "human")
[1] "Read in and process NicheNet's networks"
[1] "Define expressed ligands and receptors in receiver and sender cells"
[1] "Perform DE analysis in receiver cell"
Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: condition1
