### ISSUE TITLE
Error in get_expressed_genes(receiver, seuratObj_tLB) : One or more provided cell clusters is not part of the 'Idents' of your Seurat object

### ISSUE THREAD

**Issue by superman2412** [saeyslab/nichenetr#101]
Hi, 

Really grateful to you for development of a fantastic tool such as NicheNet!

Unfortunately, I am getting an error as follows: 

<img width="881" alt="Screenshot 2021-08-23 at 05 49 45" src="https://user-images.githubusercontent.com/78153664/130427368-97cd05f1-c9aa-473a-969e-cbfef1eea466.png">

Can you please shed some light on how to fix this error?

Here's some more information on how my Seurat object looks like:

<img width="886" alt="Screenshot 2021-08-23 at 05 50 45" src="https://user-images.githubusercontent.com/78153664/130427519-35bee296-5fcd-4b23-b690-ba084d9e8dba.png">

<img width="871" alt="Screenshot 2021-08-23 at 05 50 56" src="https://user-images.githubusercontent.com/78153664/130427548-deb90542-bb4d-4fc8-a1a6-ba74c0e9b505.png">

<img width="881" alt="Screenshot 2021-08-23 at 05 51 08" src="https://user-images.githubusercontent.com/78153664/130427567-5131d871-b048-40de-80d5-da8994bb4ceb.png">

<img width="885" alt="Screenshot 2021-08-23 at 05 53 01" src="https://user-images.githubusercontent.com/78153664/130427825-9f05fa74-1d05-4a94-990d-1a9ec7386198.png">

Also, I am trying to input cell subtypes into the NicheNet analysis. My sender / receiver cells belong to cell subtypes column in the Seurat object.

**Comment by superman2412** [comment]
@browaeysrobin Thank you so much for your prompt response! Really appreciate it! I tired implementing your suggestion as follows by setting the Idents of the Seurat object in question to the Cell_subtype column:

`Idents(object = seuratObj_tLB) <- seuratObj_tLB@meta.data$Cell_subtype`

And the error disappeared. But I was wondering if this is indeed the correct way to solve the error? Is there a way to verify that this is the correct way to solve the problem?

**Comment by browaeysrobin** [comment]
Hi @superman2412 

You can check whether the cell names and their linked identities are the same as their cell type annotations. This should be OK.
If I change Seurat identities, I use the `SetIdent` function of Seurat, but I think your solution should be OK as well.

**Comment by superman2412** [comment]
Thank you so much! Really appreciate the prompt correspondence.
