### ISSUE TITLE
Inferring ligand-to-target signaling paths on mouse genes

### ISSUE THREAD

**Issue by Sergio-ote** [saeyslab/nichenetr#104]
Hi nichenetr team!
first of, this is rather a biological than a technical question.

I am using your very detailed vignettes of the tool to work on my scRNA-seq mouse data. The Seurat vignette has worked perfectly, and now I was wondering if I could also run the "Inferring ligand-to-target signaling paths" on this mouse data. Nevertheless, the vignette only applies to human data. Now, two questions:
- Accepting that signalling pathways might have differences between the two species, would it be appropriate to run the script using mouse data? I assume so because initially we are converting the human genes of the pre-builts to mouse.
- If I am right on my first assumption, is it better to convert the mouse genes to human, or do the same conversion of the pre-builts of this vignette to mouse?
 
Since the genes with no ortholog will be dropped out during the conversion, I was wondering which would be the best approach.

Thank you for your time and congratulations for the tool.

Sergio

**Comment by browaeysrobin** [comment]
Hi @Sergio-ote 

Sorry for the late reply, I was on holiday the last 3 weeks.

This is a very good question.
Important to know is that the NicheNet networks and ligand-target model are mainly built from human databases (and a limited number of mouse databases for which the gene symbols were converted to their human ortholog). If thus falsely assumes that pathways etc are the same for mouse and human, but at the time we did not find enough mouse-specific databases to build a separate mouse model that takes into account differences in signaling between both species. Therefore, genes with no ortholog will be dropped out indeed if you use the default NicheNet networks.

For reasons related to running time, I would suggest that you convert the mouse gene symbols of your genes of interest to their human orthologs (converting the networks etc from human to mouse would take more time).
