### ISSUE TITLE
Incomplete "ligand_target_matrix"

### ISSUE THREAD

**Issue by fritzherbert** [saeyslab/nichenetr#105]
Hi,

I have built an expanded ligand-target model for my analysis. However, when I do so using your vignette, I seem to lose the majority of the data contained in the original "weighted_network". This seems to be partly due to the fact that the available "ligand_target matrix" and "lr_network" datasets only comprise 688 ligands even though there are much more interactions recorded in the weighted networks. Is there somewhere I could download the complete "lr_network" and "ligand_target_matrix" used to make the complete "weighted_network" ?

**Comment by browaeysrobin** [comment]
Hi @fritzherbert 

If I understand it correctly, you used the vignette https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md to build an own ligand-target model, right?

Can you explain in more detail what you mean with "I seem to lose the majority of the data contained in the original "weighted_network" ". If you custom data sources to make your custom model do not include all interactions in the NicheNet networks, then you will lose some information in the original weighted network of course.

**Comment by fritzherbert** [comment]
Of course! 

I use that vignette yes. 
At the following step in the vignette: 

```{r}
# aggregate the individual data sources in a weighted manner to obtain a weighted integrated signaling network
weighted_networks = construct_weighted_networks(lr_network = new_lr_network, sig_network = new_sig_network, gr_network = new_gr_network, source_weights_df = new_source_weights_df)
```

I am asked to construct a new weighted network using the newly made lr_network and new sig_network. 

To make both of these, I use the lr_network, gr_network and sig_network I found here and add my own entries: https://github.com/saeyslab/nichenetr/blob/master/data/lr_network.rda
https://github.com/saeyslab/nichenetr/blob/master/data/gr_network.rda
https://github.com/saeyslab/nichenetr/blob/master/data/sig_network.rda

Each of these has about 12000 entries. 

The weighted_network provided originally has about 2.500.000 entries: 
weighted_networks = readRDS(url("https://zenodo.org/record/3260758/files/weighted_networks.rds"))

So, when I make my own weighted_networks using the code above, my weighted network only has about 30.000 entries. 

Thus I am wondering how to not lose all the information contained in the original weighted_network

**Comment by browaeysrobin** [comment]
Hi @fritzherbert 

You should use the lr_network, gr_network and sig_network from the zenodo website as indicated in the vignettes. You used the internal ones, which are used by the package for unit testing but they are not complete and should not be used in applications.

**Comment by fritzherbert** [comment]
Could you please direct me to them ? 

I have looked for them before but cannot find them...

Thank you!

**Comment by browaeysrobin** [comment]
It is in the vignette itself

`
# The complete networks can be downloaded from Zenodo
lr_network = readRDS(url("https://zenodo.org/record/3260758/files/lr_network.rds"))
sig_network = readRDS(url("https://zenodo.org/record/3260758/files/signaling_network.rds"))
gr_network = readRDS(url("https://zenodo.org/record/3260758/files/gr_network.rds"))
`
Which takes a download from here:
https://zenodo.org/record/3260758
