### ISSUE TITLE
Receptors of top-ranked ligands

### ISSUE THREAD

**Issue by 1378989** [saeyslab/nichenetr#109]
Hi NicheNet team,

Very great package that you have developed thank you!

I would have a question about picture of the receptors of top-ranked ligands,Could you help me to give me a more detailed explanantion about how to understand the differences  and meanings of the pictures. 

Thanks for your support and have a nice day,

Rachel
![image](https://user-images.githubusercontent.com/85168692/139275792-622a578c-d89d-47e0-a4ca-cecb4e1b959f.png)
![image](https://user-images.githubusercontent.com/85168692/139275861-b20ec5ca-cb05-4e50-8e7a-df73b001c970.png)

**Comment by browaeysrobin** [comment]
Hi @1378989 

Please have a look at these sections of the FAQ and let me know if you would still have specific questions about this

https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#if-i-look-at-the-ligand-receptor-network-i-see-some-low-interaction-scores-between-highly-expressed-ligand-receptor-interactions-or-some-high-scores-between-lowly-expressed-pairs-what-is-the-reason-for-this

https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#in-the-seurat-vignette-you-show-some-code-to-define-bona-fide-ligand-receptor-interactions-but-i-see-that-some-ligand-receptor-pairs-that-are-not-considered-bona-fide-have-higher-prior-interaction-scores-than-some-bona-fide-pairs-how-is-this-possible-if-the-prior-interaction-score-is-based-on-the-confidence-of-the-prior-information-should-bona-fide-pairs-not-have-the-highest-scores
