### ISSUE TITLE
receptors info for all ligands identified

### ISSUE THREAD

**Issue by yxiao832** [saeyslab/nichenetr#11]
Hi Nichenetr group,
Thanks for this nice package!
I wonder how I can pull out the receptor information which is not only for the top ligands? 
Thanks!
Yang

**Comment by browaeysrobin** [comment]
Hi @yxiao832 
Via this command: lr_network %>% filter(from %in% expressed_ligands & to %in% expressed_receptors) (step3 in https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md or step3 in https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_activity_geneset.md)
