### ISSUE TITLE
Inferring ligand-to-target signaling paths

### ISSUE THREAD

**Issue by fritzherbert** [saeyslab/nichenetr#110]
Hi,
In the follow up analysis. Where we look at signalling paths of different ligands and transcription factors. I don't understand if these are mRNA interactions or actual proteins that are interacting? Furthermore, why are some of the dashed lines blue and some of them are red ? 

All the best,

Fritz

**Comment by browaeysrobin** [comment]
Hi @fritzherbert 

Red edges indicate signaling/physical interactions between the protein products of the genes.
Blue indicate gene regulatory interactions between the protein product of the source node, and the gene of the target node
