### ISSUE TITLE
No DEG for nichennet_surat_aggregate()

### ISSUE THREAD

**Issue by Kiliankleemann** [saeyslab/nichenetr#112]
Dear Robin,

I have carried out the fundamental NichentR analysis from Seurat and al works very well. 
I get roughly 50 DEGs for geneset_oi for my receiver cells. 

However when I carry out the nichenet_seurat_aggregate function (for circlos visualization) there are no DEGs.

Screenshot of my R-Result and Error message
<img width="649" alt="grafik" src="https://user-images.githubusercontent.com/85544476/142887619-8b79ea2b-d924-4ee2-9808-0a8b95683a96.png">

Do you have any suggestions? 

Kind regards
Kilian

**Comment by browaeysrobin** [comment]
Hi @Kiliankleemann 

For the moment I have not enough information about how you did things to find an explanation for the differences you observe.
Can you provide the source code of how you got 50 DEGs with 'the fundamental' analysis, and what you used as input for the `nichenet_seurat_aggregate` function?
Also read the explanation of the different parameters of this last function carefully. Normally the code used in the step-by-step analysis vignette is nearly the same as the wrapper function. Different input in some parameter probably explains the difference you observe.

Also note: you don't need to use a wrapper function before making circos plots, you can do that after a step-by-by step analysis as well. Just be aware what output corresponds to what.
