### ISSUE TITLE
Gene set of interest used as input for NicheNet: should both up and down regulated be included?

### ISSUE THREAD

**Issue by mjgomezv** [saeyslab/nichenetr#113]
Hi, 

I am choosing my gene set of interest to run nicheNet. I am using differentially expressed genes between two conditions as an input, and I was wondering whether I should keep only upregulated genes, or if it is ok to include both up and down-regulated. As far as I understand from the vignettes both are included, but just wanted to confirm this. 

Many thanks!
Maria

**Comment by browaeysrobin** [comment]
Hi @mjgomezv 

Since ligands can induce both downregulation and upregulation of genes, I generally suggest keeping both in the geneset. But if you for dataset-specific reasons think that only taking upregulated genes is better, that's OK of course.
