### ISSUE TITLE
Source of sig_network and gr_network?

### ISSUE THREAD

**Issue by realzehuali** [saeyslab/nichenetr#114]
Thanks for the great package!
I was trying to construct my own ligand_target_matrix model using the vigenette of model_construction.Rmd.
I was able to build my own interested ligand target pairs and saved as lr_network. The lr_network I built was not large and included only few pairs I concerned. However, the ligand was not in the sig_network$from or sig_network$to, nor in either gr_network$from or gr_network$to.
So I was wondering if I could expand the sig_network and gr_network based on the source of them. Or there might be other ways of doing it.
Thanks for any help!

**Comment by adesalegn** [comment]
Hi browaeysrobin;

I have the same question and incase you have time, I would appreciate your help.
I was adding some ligand-receptor interaction to the existing data as you indicated at(https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md).
However, running the code below produced an error. 
[ ligand_target_matrix = construct_ligand_target_matrix(weighted_networks = weighted_networks, ligands = ligands, 
                                                       algorithm = "PPR", damping_factor = hyperparameter_list$damping_factor, 
                                                     ltf_cutoff = hyperparameter_list$ltf_cutoff)  
](url)
The error is here 
[Error in igraph::page_rank(G, algo = c("prpack"), vids = igraph::V(G),  : 
  At prpack.cpp:55 : the sum of the elements in the reset vector must not be zero, Invalid value](url)

Thank you so much for your help!!

**Comment by browaeysrobin** [comment]
Hi @realzehuali 

> Thanks for the great package! I was trying to construct my own ligand_target_matrix model using the vigenette of model_construction.Rmd. I was able to build my own interested ligand target pairs and saved as lr_network. The lr_network I built was not large and included only few pairs I concerned. However, the ligand was not in the sig_network$from or sig_network$to, nor in either gr_network$from or gr_network$to. So I was wondering if I could expand the sig_network and gr_network based on the source of them. Or there might be other ways of doing it. Thanks for any help!

If the receptor(s) of the newly added ligand is part of the sig_network, then there will be no problem to predict target genes of this ligand. So you should thus not expand the sig_network and gr_network yourself (you could of course if you would want to)

**Comment by browaeysrobin** [comment]
> I have the same question and incase you have time, I would appreciate your help.
> I was adding some ligand-receptor interaction to the existing data as you indicated at(https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md).
> However, running the code below produced an error.

Probably, your input format of the ligands for which you want to build the ligand-target matrix is not correct.
It should be in a list format, with each ligand representing a sublist.

You can easily do this as follows (starting from character vector of ligands)
`ligands_list <- lapply(ligands_vector, function(x){x})`

**Comment by adesalegn** [comment]
Hi Robin Browaeys,

Thanks so much for your help and now I am running it on the server and I
will let you know if I get the error. In the meantime, I would like to ask
the question maintained by user realzehuali.
In my case, the receptor of the newly added ligand  is not the part of both
sig_network and gr_network. So how am I supposed to include them in  both
networks? I could not find anyways how to do that in the vigenette.

Thank you again!

Best,
Amare

**Comment by browaeysrobin** [comment]
Hi @adesalegn 

> In my case, the receptor of the newly added ligand is not the part of both sig_network and gr_network. So how am I supposed to include them in both networks? I could not find anyways how to do that in the vigenette.

If there is no link known between that receptor, and downstream signaling proteins/transcription factors/... you won't be able to predict target genes for that ligand signaling through that receptor.
The only thing you can do then is updating the sig_network yourself to include new signaling data sources that include this receptor, and link this to downstream proteins.

May I ask what the gene symbol is of that receptor? Then I can check whether it is part of the networks that I am now updating myself for the NicheNet v2 model.

**Comment by adesalegn** [comment]
Hi Robin, actually I was looking at the omnipath ligand-receptor network
(From Omnipath R package) and comparing it with your lr_network.
So basically, I am merging both and see if I get different results. I am
looking very much forward to seeing the new version of NicheNet v2.

Best, ad

**Comment by browaeysrobin** [comment]
> Hi Robin, actually I was looking at the omnipath ligand-receptor network (From Omnipath R package) and comparing it with your lr_network. So basically, I am merging both and see if I get different results. I am looking very much forward to seeing the new version of NicheNet v2.

Hi @adesalegn 

The NicheNet v2 model will be based on the OmniPath ligand-receptor network (but filtered in a smart way to reduce some of the bad annotations and links that are present there), and also other new data sources like HumanNet, HuRi, KnockTF, ReMap2021, ...
We will likely release it in February/March, together with a new NicheNet extension.

**Comment by realzehuali** [comment]
Looking forward to NicheNet v2!
