### ISSUE TITLE
How to use NicheNet in Visium data 

### ISSUE THREAD

**Issue by lengfei5** [saeyslab/nichenetr#118]
Hi there,

Now I have Visium data and single cell RNA-seq data, and I am wondering how to run NicheNet in such a way that the spatial information from Visium data is also taken into account.

Thanks. 
Best,
Jingkui

**Comment by browaeysrobin** [comment]
Hi @lengfei5 

It is very hard to do this "automatically" in one workflow. As far as I know, no methods have been developed that go directly and fluently from Visium and scRNAseq integration to spatially informed cell-cell communication inference.

What has been done though (eg in the papers https://www.nature.com/articles/s41588-021-00972-2 or less directly in https://www.sciencedirect.com/science/article/pii/S0092867421014811), is spatially mapping your cell types from the scRNAseq data on your Visium data (or other spatial data), and using these mappings to find which cell types co-localize together. Then you give these co-localized cell types as input in cell-cell communication algorithms like CellPhoneDB and NicheNet. In that way, you only look for cell-cell signaling patterns between cell types that are located in the same neighborhoods/niches/microenvironments. So, in this type of analysis, you use your spatial data to get a better definition of sender and receiver cell types. This avoids that the algorithm tries to predict interactions between cells that physically don't interact. For cell type mapping through integration of Visium and scRNAseq, I recommend using RCTD (https://github.com/dmcable/spacexr/blob/master/README.md) or Cell2Location (https://github.com/BayraktarLab/cell2location).

Another interesting type of spatially-aware cell-cell communication analysis is the following:
If you different subtypes of the same cell type are located in a different location (so with different other cell types in their neighborhood), you can ask how these different neighborhoods result in the gene expression differences between these subtypes. To tackle this question, you can use NicheNet with the location-specific ligands / sender celltypes as input, and the DE genes between the spatial subtypes as geneset of interest. You can use the basic or Differential NicheNet workflow for this: 
https://github.com/saeyslab/nichenetr/blob/master/vignettes/differential_nichenet.md. 

But realize that for all these questions, you will need to "spatially annotate" your scRNAseq celltypes yourself based on your Visium data.

**Comment by lengfei5** [comment]
Dear @browaeysrobin , 

I really appreciate that you share generously your insight into my question.
That helps me so much to clarify how to start my analysis.
Yes, I have annotated our Visium data with scRNA-seq using RCTD, which works nicely for now. 
I will pre-select the cell types from the same/neighboring spots in the area of interest, as input for NicheNet.

Thanks again.

Best,
Jingkui
