### ISSUE TITLE
Incompatible with Seurat V3

### ISSUE THREAD

**Issue by etbuface** [saeyslab/nichenetr#119]
Dear Robin,
It's really good work and appreciates it!  I have noticed that you have done great efforts for the suitability of Seurat V4, such as #67, #74. However, it seemed that there was some defect to the compatibility with Seurat V3 which mainly appeared in the conflict of avg_logFC(V3) or avg_log2FC(V4) in some functions. So I had to edit some functions which relate to the avg_log2FC. Hope that there could be a judgment for the version of Seurat in a further update, so the functions could be more adaptable.

**Comment by browaeysrobin** [comment]
Hi @etbuface 

Can you mention the specific functions? Is it possible that those are all Differential NicheNet functions? Because I thought having implemented the Seurat version test for all other functions (but I could have forgotten some of course)

**Comment by etbuface** [comment]
Hi @browaeysrobin 

I was using the beta extension Differential NicheNet in which I found some of functions (e.g. calculate_niche_de, process_niche_de) in this section related to the avg_log2FC (V4).

**Comment by browaeysrobin** [comment]
Hi @etbuface 

All the differential NicheNet functions should be Seurat v3 compatible now.
