### ISSUE TITLE
from where the pearson correlation values of the ligand activity comes?

### ISSUE THREAD

**Issue by adesalegn** [saeyslab/nichenetr#120]
Dear Nichenets Teams,

I have a burning question that I do not understand fully, that is, how did you do the correlation to predict ligand activity. 
The paper says, "the correlation is between the ligand-target regulatory potential scores of each selected ligand and the target indicator vector, which indicates whether a gene belongs to the gene set of interest or not. " 

To my understanding correlation is between two numeric vectors and here in the `predict_ligand_activities()` function  we only input a character vector for `geneset`, `background_expressed_genes `and `potential_ligands `arguments. So I wonder where the correlation value comes from(between what and what)?

```
ligand_activities <- predict_ligand_activities(
  geneset = geneset_oi, 
  background_expressed_genes = background_expressed_genes, 
  ligand_target_matrix = ligand_target_matrix, 
  potential_ligands = potential_ligands) 
```

best
amare

**Comment by browaeysrobin** [comment]
Hi @adesalegn 

Under the hood of this function the following happens:
1) genes from `geneset` and `background_expressed_genes` are merged together in one vector
2) if a gene belongs to the `geneset`, it gets a value of 1, if a gene belongs to the `background_expressed_genes` it gets a score of 0. (=numeric response vector)
3) for each ligand, we extract the the regulatory potential scores (from the `ligand_target_matrix`) for these genes (=numeric prediction vector)
4) we calculate the pearson correlation between the prediction vector from 3) en the response vector from 2) 
5) repeat 3) en 4) for all other ligands of `potential_ligands`

**Comment by adesalegn** [comment]
Hi @browaeysrobin, Thank you so much. So if I understand correctly, the correlation is basically between a vector with a zero and one value of the combined `geneset` and `background_expressed_genes`  genes and the ligand genes with the values of potential regulatory score extracted from ` ligand_target_matrix`. 

Besides, I am afraid I got the 5th point you mentioned. I would appreciate it if you could explain this?  

Thank you!
amare

**Comment by browaeysrobin** [comment]
Yes indeed

For the fifth point: we calculate the correlation between the geneset and the regulatory potential scores of ligand A to get activity values for ligand A, then we do that for ligand B to get activity values for ligand B, then for ligand C etc until we get activity values for all ligands in the potential ligands vector

**Comment by adesalegn** [comment]
Thank you so much, Robin, for your answer.
I am not sure if this is a good question, but I wonder if there is a way to compute the expression value for the `geneset `and `background_expressed_genes` to get the response vector and the same for the `ligand `to get the predictor vector then see the correlation.   Thank you again!!

**Comment by browaeysrobin** [comment]
We tried that out, but it did not work better on our ligand-treatment dataset benchmark (on the contrary)

**Comment by adesalegn** [comment]
Thank you so much for answering all my questions and if  I have more question I will come again.
