### ISSUE TITLE
Ligand activity errors

### ISSUE THREAD

**Issue by gregszetoAI** [saeyslab/nichenetr#124]
Hello,

I am getting the below error message after running **get_ligand_activities_targets**. However, the function still outputs results that are non-zero/not the same. I am running this only as a DE to infer ligand activities in 2 different conditions of receivers. Do you have any suggestions for places to check for the source of error?:
```
Warning message in evaluate_target_prediction(setting, ligand_target_matrix, ligands_position):
“all target gene probability score predictions have same value”
Warning message in cor(prediction, response):
“the standard deviation is zero”
Warning message in cor(prediction, response, method = "s"):
“the standard deviation is zero”
```

**Comment by browaeysrobin** [comment]
Hi @gregszetoAI 

These are warning messages, and not error messages.
The warning comes from 1 or 2 ligands in the ligand-target matrix that have the same prediction value across all evaluated genes. You should not worry about that.
