### ISSUE TITLE
calculate_niche_de() function not found

### ISSUE THREAD

**Issue by quanphan08** [saeyslab/nichenetr#125]
Hello,

Thank you for making and maintaining this awesome package!
I was following the vignette for differential conditions and bumped into the problem that for some reasons the calculate_niche_de() was not installed along with the nichenetr.
I was able to find the function code in github, but I was wondering if there was something that I missed while installing it the first time?

Best,
Quan

**Comment by browaeysrobin** [comment]
The differential NicheNet code was only added recently. Can you try reinstalling nichenetr to its new version? And let me know whether this resolved the issue?
