### ISSUE TITLE
Display the differential interaction pairs between different groups 

### ISSUE THREAD

**Issue by Biglinboy** [saeyslab/nichenetr#129]
@browaeysrobin Hello, very glad to finally see you develop the software,I have a question to ask:

I am using nichenet through seurat and I was wondering whether it's possible to get a metric/score of interaction per cell type in  different groups .Because I have not find group info of ligand_receptor pair in nichenet_output$ligand_receptor_df, but I need to display these difference of interaction pairs between different groups. What I need to do?

Thanks you in advance for your help.

liny

**Comment by browaeysrobin** [comment]
Hi @Biglinboy 

I assume that you used `nichenet_seuratobj_aggregate` ?

In that case you need to define a group of interest vs a reference group. You can run the analysis for each of your groups as group of interest, and use the ligand activity scores as "interaction score" for that group. But be aware that you know to interpret the ligand metrics etc. 

In case you also want to include differential expression of the ligands and receptors next to ligand activities, you can check out the Differential NicheNet vignette: https://github.com/saeyslab/nichenetr/blob/master/vignettes/differential_nichenet_pEMT.md
