### ISSUE TITLE
"False" Bona fide ligand

### ISSUE THREAD

**Issue by Yuxiiii** [saeyslab/nichenetr#130]
Hi browaeysrobin,

Thanks for the awesome package and instruction!

I tried to test the ligands presented in the combination plot by filtering them out of ligand_activities matrix. However, I found some of ligands are FALSE in bona_fide column. Does this mean that there is something wrong with my analysis? 

If this is the normal situation, do you think I should get rid of these "false" ligands? 

Best, 
Yuxiiiii

**Comment by browaeysrobin** [comment]
Hi @Yuxiiii 

No worries, you did nothing wrong.

Depending on what you are looking for, you can remove these bona-fide-false ligands or not, see this question-answer about this on the FAQ page: 
https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#in-the-seurat-vignette-you-show-some-code-to-define-bona-fide-ligand-receptor-interactions-but-i-see-that-some-ligand-receptor-pairs-that-are-not-considered-bona-fide-have-higher-prior-interaction-scores-than-some-bona-fide-pairs-how-is-this-possible-if-the-prior-interaction-score-is-based-on-the-confidence-of-the-prior-information-should-bona-fide-pairs-not-have-the-highest-scores
