### ISSUE TITLE
Trouble with get_prioritization_tables

### ISSUE THREAD

**Issue by jenzieba** [saeyslab/nichenetr#131]
Hello and thank you for your wonderful work so far. 

I am using 10x single cell data comparing two conditions. Everything is working fine until i get to almost of the end of the tutorial with my data
```{r}
exprs_sender_receiver = lr_network %>% 
  inner_join(exprs_tbl_ligand, by = c("ligand")) %>% 
  inner_join(exprs_tbl_receptor, by = c("receptor")) %>% inner_join(DE_sender_receiver %>% distinct(niche, sender, receiver))
  
ligand_scaled_receptor_expression_fraction_df = exprs_sender_receiver %>% group_by(ligand, receiver) %>% mutate(rank_receptor_expression = dense_rank(receptor_expression), rank_receptor_fraction  = dense_rank(receptor_fraction)) %>% mutate(ligand_scaled_receptor_expression_fraction = 0.5*( (rank_receptor_fraction / max(rank_receptor_fraction)) + ((rank_receptor_expression / max(rank_receptor_expression))) ) )  %>% distinct(ligand, receptor, receiver, ligand_scaled_receptor_expression_fraction, bonafide) %>% distinct() %>% ungroup() 



prioritizing_weights = c("scaled_ligand_score" = 5,
                         "scaled_ligand_expression_scaled" = 1,
                         "ligand_fraction" = 1,
                         "scaled_ligand_score_spatial" = 2, 
                         "scaled_receptor_score" = 0.5,
                         "scaled_receptor_expression_scaled" = 0.5,
                         "receptor_fraction" = 1, 
                         "ligand_scaled_receptor_expression_fraction" = 1,
                         "scaled_receptor_score_spatial" = 0,
                         "scaled_activity" = 0,
                         "scaled_activity_normalized" = 1,
                         "bona_fide" = 1)

output = list(DE_sender_receiver = DE_sender_receiver, ligand_scaled_receptor_expression_fraction_df = ligand_scaled_receptor_expression_fraction_df,
         ligand_activities_targets = ligand_activities_targets, DE_receiver_processed_targets = DE_receiver_processed_targets, exprs_tbl_ligand = exprs_tbl_ligand,  exprs_tbl_receptor = exprs_tbl_receptor, exprs_tbl_target = exprs_tbl_target)
prioritization_tables = get_prioritization_tables(output, prioritizing_weights)

Error in `auto_copy()`:
! `x` and `y` must share the same src.
set `copy` = TRUE (may be slow).
Backtrace:
  1. nichenetr::get_prioritization_tables(output, prioritizing_weights)
 10. dplyr:::inner_join.data.frame(...)
 11. dplyr::auto_copy(x, y, copy = copy)
 Error in auto_copy(x, y, copy = copy) : 
set `copy` = TRUE (may be slow).
```

I have no idea how to resolve this, any help would be appreciated thank you!
-Jen Zieba

**Comment by browaeysrobin** [comment]
Hi @jenzieba 

Without having access to the objects myself, I cannot say what went wrong here.

But I can give some pointers to what you can look at to identify the problem.
The error message indicates there is a problem in joining some of the data frames in the output list. Therefore, I would suggest to have a closer look in each of these data frame, check whether they are not empty, use the same celltype and group labels in all tables etc.

**Comment by browaeysrobin** [comment]
@jenzieba

**Comment by gcIL20** [comment]
I'm also having this problem, I've checked the dfs and all look fine. They're all full, they all have the same celltype and group labels. 


```
<error/rlang_error>
Error in `auto_copy()`:
! `x` and `y` must share the same src.
i set `copy` = TRUE (may be slow).
---
Backtrace:
  1. nichenetr::get_prioritization_tables(output, prioritizing_weights)
 10. dplyr:::inner_join.data.frame(...)
 11. dplyr::auto_copy(x, y, copy = copy)
Run `rlang::last_trace()` to see the full context.

```

**Comment by browaeysrobin** [comment]
Hi @gcIL20 

Can you show me the first rows you have for  `sender_spatial_DE_processed` and `receiver_spatial_DE_processed` ?

**Comment by gcIL20** [comment]
I don't have either of those, as I am not using spatial data. I also excluded them from the output list in the same way [jenzieba](https://github.com/jenzieba) did.

**Comment by browaeysrobin** [comment]
Hi @gcIL20 

That's likely the reason for your error and the error of @jenzieba 

In paragraph 3 of the vignette:
https://github.com/saeyslab/nichenetr/blob/master/vignettes/differential_nichenet.md#3-optional-calculate-differential-expression-between-the-different-spatial-regions

it shows what to do if you don't have spatial information -- this will generate mock dataframes that can be joined later on together with the other dataframes in the `get_prioritization_tables` (so these mock dataframes need to be in the `output` list). If you follow all these steps strictly, you should not get an error. 

I agree that this is not very user-friendly, and I will change the vignette and make `get_prioritization_tables` more flexible in the future.

**Comment by gcIL20** [comment]
Thanks, I will try and report back if it works! I shouldn't have skipped steps thinking they weren't relevant.
