### ISSUE TITLE
Indices error when gene dimension % 100 == 1

### ISSUE THREAD

**Issue by Arlene-1998** [saeyslab/nichenetr#132]
https://github.com/saeyslab/nichenetr/blob/a8013f07ae8db3a0c9539b394ce20cf95ee4c900/R/application_prediction.R#L1281

When number of genes % 100 == 1, the up mentioned line will raise an error. Maybe "drop=FALSE" can solve this.

**Comment by browaeysrobin** [comment]
@Arlene-1998
