### ISSUE TITLE
Cannot install in macos

### ISSUE THREAD

**Issue by meg-bit** [saeyslab/nichenetr#133]
Hello, 

The package does not install on macos. It returns "non-zero exit status". And I cannot load the library. 
```
Warning message in i.p(...):
“installation of package ‘nloptr’ had non-zero exit status”
Warning message in i.p(...):
“installation of package ‘lme4’ had non-zero exit status”
Warning message in i.p(...):
“installation of package ‘pbkrtest’ had non-zero exit status”
Warning message in i.p(...):
“installation of package ‘car’ had non-zero exit status”
Warning message in i.p(...):
“installation of package ‘rstatix’ had non-zero exit status”
Warning message in i.p(...):
“installation of package ‘ggpubr’ had non-zero exit status”
```

**Comment by meg-bit** [comment]
Hi @browaeysrobin ,
Thank you!

I already tried that, which did not work. I am using macOS Monterey Version 12.2.1.  I also tried Xcode and GCC to compile and did not solve the problem.

**I can use other R and Bioconductor packages with no problem.**

**Comment by browaeysrobin** [comment]
Then the problem seems to be related to nloptr instead of nichenetr. So best to troubleshoot there, and contact the developers of nloptr.
