### ISSUE TITLE
Trouble with get_expressed_genes/nichenet_seuratobj_aggregate

### ISSUE THREAD

**Issue by Guanxin1996** [saeyslab/nichenetr#134]
Hi，
I‘m using 10x single cell data  from seurat. I follow the tutorial https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_wrapper.md and https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md，but i have an error with get_expressed_genes only in some cell types（eg.Vascular smooth muscle cell 1） and in others cell types（eg.Dendritic Cells） it does work
```
 nichenet_output = nichenet_seuratobj_aggregate(
+   seurat_obj = scRNA, 
+   receiver = "Monocytes and macrophages", 
+   condition_colname = "sample", condition_oi = "AC", condition_reference = "PA", 
+   sender = c("Vascular smooth muscle cell 1","Vascular smooth muscle cell 2", "Vascular smooth muscle cell 3"), 
+   ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "human")
[1] "Read in and process NicheNet's networks"
[1] "Define expressed ligands and receptors in receiver and sender cells"
Error in apply(., 1, function(x) { : dim(X) must have a positive length

 receiver = "Dendritic Cells"
 expressed_genes_receiver = get_expressed_genes(receiver, scRNA, pct = 0.10)
 background_expressed_genes = expressed_genes_receiver %>% .[. %in% rownames(ligand_target_matrix)]

 receiver = "Vascular smooth muscle cell 1"
 expressed_genes_receiver = get_expressed_genes(receiver, scRNA, pct = 0.10)
Error in apply(., 1, function(x) { : dim(X) must have a positive length
```
I don't know what the problem is, hope to get your help.
Thanks！

**Comment by browaeysrobin** [comment]
Hi @Guanxin1996 

Can you give me information about the number of cells per condition for the cell types that cause an error?

I will also check whether this might be related to issue #132

**Comment by Guanxin1996** [comment]
The number of cells per condition for the cell types that cause an error are 
Monocytes and macrophages 8354 ,
T Cells 1 17382 ,
EC2 5008 ,
Vascular smooth muscle cell 1 5220.
It looks like too many numbers are the cause of the error,beacause others are less than these.

**Comment by browaeysrobin** [comment]
Hi @Guanxin1996 

Sorry if my question before was not clear, but can you give me the number of cells for each condition - so the number of cells in your condition_oi `AC` and in your condition_reference `PA` ?

Normally having many cells should not lead to errors.

**Comment by browaeysrobin** [comment]
Hi @Guanxin1996 
This is probably related to #139 

I updated nichenetr to try to fix this. Can you check whether it works now or now after re-installing?

**Comment by browaeysrobin** [comment]
Hi @Guanxin1996 

Any update on this?
