### ISSUE TITLE
Differential ligand expression analysis

### ISSUE THREAD

**Issue by kelvinlee760948065** [saeyslab/nichenetr#136]
As examples you provided, you just focus on differential receptor expression of different cell types. But how to realize differential ligand expression analysis of different cell types? For example, I want to detect chemokines of different subtypes of tumor cells in order to  access their ability of  immune cell recruitment?

**Comment by browaeysrobin** [comment]
Hi @kelvinlee760948065 

I'm very sorry but I don't understand your question entirely. 
1) I guess you are talking about the Differential NicheNet vignettes?
2) In the current Differential NicheNet pipeline, differential expression of ligands in sender cell types is included I think? So I don't see how the code provide there cannot help you for your question.

**Comment by kelvinlee760948065** [comment]
您的邮件我已收到，但如果重要通知请以我亲自回复收到为准！感谢！
