### ISSUE TITLE
Problem with large datasets?

### ISSUE THREAD

**Issue by MairFlo** [saeyslab/nichenetr#14]
Hi there, first: thank you for this awesome package! I really think this is a tool that allows for potentially much more meaningful interpretation of single cell data.

I am running into an issue with larger data sets though. When I follow the vignette starting from a Seurat object, all would be working fine as long as I keep the cell number below 50-60k cells. When running anything above 90k cells (my full dataset would be more than 150k cells), the "get_expressed_genes" command for the receiver runs into the following issue:

expressed_genes_receiver = get_expressed_genes(receiver, Nichenet.CD3, pct = 0.10)
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

I have googled the error, and it seems to be a very generic error message, so I do not really know how I could fix that. Thank you in advance for any help!

PS: I am running on an iMac Pro, Xeon W 3.2Ghz, 64GB RAM, MacOS 10.14.6, R 3.6.2.

**Comment by zhongyiwang1** [comment]
I encountered the same problem, and hope there is a way to resolve this.

**Comment by browaeysrobin** [comment]
Hi @MairFlo and @zhongyiwang1,

Thank you for pointing this out! I will be trying out some solutions and keep you updated!

**Comment by browaeysrobin** [comment]
Hi @MairFlo and @zhongyiwang1 

I adapted the code of `get_expressed_genes()` to make it better in handling large datasets. I tried it out on a dataset of 11k and it worked fine. Can you check whether it works for you now (after reinstalling nichenetr)?

In the future, I also plan to write a function that gives the possibility to perform some downsampling.

**Comment by zhongyiwang1** [comment]
Hi @browaeysrobin,
Thanks a lot for your speedy response and action!! It now works fine for me.
Many thanks for developing this amazing package as well.
