### ISSUE TITLE
Comparing ligand activity scores across clusters

### ISSUE THREAD

**Issue by mjgomezv** [saeyslab/nichenetr#140]
Hi, 

I am performing NicheNet analysis in several clusters of my single cell ran seq data. I want to compare my ligands' PCC values between different clusters, e.g. find out whether TNF PCC in cluster A is higher than TNF PCC in cluster B. Does it make sense to do this directly? or do I need to normalise in some way? And what about comparing against TNF PCC in cluster C if cluster C comes from a different dataset? 

Many thanks!
Maria

**Comment by browaeysrobin** [comment]
Hi @mjgomezv 

In theory it makes sense to look at the absolute values of the ligand activities.

But based on my experience with many datasets, the relative rankings of the ligand activity values tells more than the absolute value of the pearson correlation. So I would suggest you normalize the ligand activity values per cluster/dataset and comparing these values.
