### ISSUE TITLE
trouble with downloading ligand_target_matrix

### ISSUE THREAD

**Issue by mimisikai** [saeyslab/nichenetr#143]
> ligand_target_matrix = readRDS(url("https://zenodo.org/record/3260758/files/ligand_target_matrix.rds"))
Error in readRDS(url("https://zenodo.org/record/3260758/files/ligand_target_matrix.rds")) : 
  cannot read from connection
In addition: Warning message:
In readRDS(url("https://zenodo.org/record/3260758/files/ligand_target_matrix.rds")) :
  URL 'https://zenodo.org/record/3260758/files/ligand_target_matrix.rds': Timeout of 60 seconds was reached

BUT, lr_network and weighted_networks okay.

**Comment by browaeysrobin** [comment]
you can increase the duration of the timeout as follows:
`options(timeout=1000)`

It is also recommended to download the ligand-target matrix and other networks locally from zenodo to avoid having to do the URL download for every analysis.
