### ISSUE TITLE
Predicting target genes regulatory potential scores of ligand-receptor pairs

### ISSUE THREAD

**Issue by kehuangke** [saeyslab/nichenetr#148]
Thanks for this great package!

I want to use NicheNet to construct the target gene matrix of some interesting ligand-receptor pairs for us.

You have put an example to calculate target gene regulatory potential scores for the ligand combination TNF+IL6.
https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md

In our data, the receptor gene of TNF is LTBR.  The question is whether it's reasonable to calculate target gene regulatory potential scores of TNF-LTBP using the same functions.

All the best

**Comment by browaeysrobin** [comment]
Hi @kehuangke 

If you want to do this, I would suggest changing the ligand-receptor and signaling network to remove all interactions from TNF to other receptors, so you keep only the TNF-LTBR interaction as ligand-receptor interaction to look for downstream effects.
