### ISSUE TITLE
lack of ligand-receptor pairs like SIRPA->CD47 and CD28->Siglec-10

### ISSUE THREAD

**Issue by ahy1221** [saeyslab/nichenetr#15]
Dear developers,
Thank you for the awesome tools and very useful ligand-receptor database 
I am trying to combine nichenetr model and ligand-receptor coexpression information to develop a new way to predict cell-to-cell interaction by scRNA dataset.
However, I found that two recently reported ligand receptor pairs like SIRPA->CD47 and CD28->Siglec-10 were not included in the nichenet prior model. 
See the reference:
https://www.cell.com/trends/immunology/pdf/S1471-4906(17)30244-2.pdf
https://www.nature.com/articles/s41586-019-1456-0
I was wondering is there a plan to further update prior model by corportating much more newly discovered ligand receptor pairs ? And is there a way to build a customized nichenet-like prior model by using my prefered ligand receptor ?

Thank you 
Yao He

**Comment by browaeysrobin** [comment]
Hi @ahy1221 

We are indeed planning to update the prior model by incorporating some new and updated databases, but this will not be for the next few weeks.

In this vignette https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md,
you can see how to incorporate your new data source with new ligand-receptor pairs and build a customized NicheNet prior model. I would suggest you just add your new data source to the existing ones, and give your new data source as weight 1, and use the optimized weights for the other data sources.

Please let me know if you would have any more questions about this.
