### ISSUE TITLE
About ligands and thier target genes

### ISSUE THREAD

**Issue by ZhaohuiRuan** [saeyslab/nichenetr#150]
Dear @browaeysrobin,

Thank you for your amazing work!

I would like to ask some questions. For the genes I am interested in, are the ligands which calculated by nichnet able to upregulate them? What can i do to screen ligands that can inhibit these genes?

Thank you!

Ruan

**Comment by browaeysrobin** [comment]
Hi @ZhaohuiRuan 

The ligand-target model provides a "potential" score for regulation in general, so this includes potential for both up- and downregulation. It is thus not possible to screen for specifically inhibiting or inducing ligands.
