### ISSUE TITLE
does Differential NicheNet analysis work for bulk RNAseq

### ISSUE THREAD

**Issue by adesalegn** [saeyslab/nichenetr#151]
Hi, great package!

Does this new Differential NicheNet analysis workflow also work for bulk RNAseq? Though I learned a bit from the former NicheNet package, I could not see much difference among the top prioritized ligands across multiple groups.

Best
amare

**Comment by browaeysrobin** [comment]
Hi @adesalegn 

In theory yes, the same principles and workflow can be applied on bulk RNAseq data of sorted cell populations. But we will not make a specific vignette on this.
