### ISSUE TITLE
evaluate cell type?

### ISSUE THREAD

**Issue by ZhaohuiRuan** [saeyslab/nichenetr#156]
Dear @browaeysrobin,

Thank you for your amazing work!

I would like to ask a question.Is it posible that we can evaluated (like using "potential" score) the most posible cell type which can regulate the interested-genes in targeted cells.

Thanks

Ruan

**Comment by browaeysrobin** [comment]
Hi @ZhaohuiRuan 

Quantitatively this is not possible, but you can see by which sender cell types the top active ligands are predicted. Eg in the LMCV case study, this clearly shows a role for monocytes and DCs vs other senders.
