### ISSUE TITLE
predict_ligand_activities results 

### ISSUE THREAD

**Issue by mimisikai** [saeyslab/nichenetr#157]
Pearson results come as "pearson[,1]" that causes error. No idea if it's only my case 
Error in `mutate()`:
! Problem while computing `rank = rank(desc(pearson))`.
Caused by error in `h()`:
! error in evaluating the argument 'x' in selecting a method for function 'rank': unable to find an inherited method for function 'desc' for signature '"matrix"'
Run `rlang::last_error()` to see where the error occurred.
![Screen Shot 2022-07-13 at 12 26 02 PM](https://user-images.githubusercontent.com/4881411/178815377-60fcc459-6d75-4728-acdc-dcc66df88c01.png)

**Comment by browaeysrobin** [comment]
Hi @mimisikai,

I haven't seen this yet. 
Can you give me more details about the specific input you used for the function and the `sessionInfo()`?
