### ISSUE TITLE
Interpreting target gene rankings?

### ISSUE THREAD

**Issue by mholtz2** [saeyslab/nichenetr#159]
I had a small question about the ligand to receptor heatmap in the seurat_steps vignette and wasn't sure where else to ask. I was wondering how the ranking/order of the target genes and is determined for this chart? I understand that the ligands are ranked based on target gene predictability. Also, how is the target gene list on the figure determined, as not all target genes are present? Thanks in advance for your help.

**Comment by browaeysrobin** [comment]
Hi @mholtz2 

*The order of the target genes in the visualization is random
*how is the target gene list that is shown determined: shown are genes in the top n of predicted genes (default 250) for a ligand - and this for all ligands that are shown. See also https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#when-interpreting-the-output-ligand-target-matrix-i-see-that-not-all-my-genes-of-my-gene-set-of-interest-are-in-the-final-ligand-target-matrix-why-is-this
