### ISSUE TITLE
no significant differences of scaled ligand activity and ligand activity between conditions

### ISSUE THREAD

**Issue by sadiexiaoyu** [saeyslab/nichenetr#160]
Hi, 
I am using Differential Nichenetr, and the results showed that there is no significant differences of scaled ligand activity output between conditions, and same with ligand activity. 
I attached the plot and looking forward to reply.

Thanks in advance! 
<img width="177" alt="Screen Shot 2022-08-15 at 16 14 03" src="https://user-images.githubusercontent.com/16802530/184600262-5afa2206-a897-453c-b9bd-b8a5874364a0.png">

**Comment by browaeysrobin** [comment]
Hi @sadiexiaoyu 

In the Differential NicheNet pipeline, the ligand activity metrics are calculated based on the upregulated genes in the receiver per condition. A high activity means thus enrichment of target genes of that ligand among the upregulated genes in that condition. 

However, ligands can induce both up- and downregulation of target genes. So if ligand X is upregulated in condition 1, the target genes induced by ligand X will also be upregulated in condition 1. But if ligand X also represses some genes, these will then be downregulated in condition, meaning they will be considered to be upregulated in condition 2 (if you have only 2 conditions). In such cases, ligands can have high activity in multiple conditions even if they themselves are only regulated in one condition.

**Comment by sadiexiaoyu** [comment]
Thank you for your reply! 
Then how should I interpret the following plot? Does it mean that these ligands are important and condition 2-specific?
<img width="457" alt="Screen Shot 2022-08-16 at 07 36 20" src="https://user-images.githubusercontent.com/16802530/184746939-49d15228-71a7-4298-a606-c2cc761f9816.png">
