### ISSUE TITLE
Question different niche but similar ligand LFC heatmap

### ISSUE THREAD

**Issue by mimisikai** [saeyslab/nichenetr#166]
I'm interested in several target subpopulations. Following your tutorials, the Ligand LFC heat map shows the same L-R pairs LF in all these niches. Even if I changed receiver_oi to another subpopulation, the heatmap of ligand LFC is still the same but receptor LFC changed accordingly. Could you please give me troubleshooting? Thanks.
![Screen Shot 2022-08-25 at 4 25 37 PM](https://user-images.githubusercontent.com/4881411/186786055-e4abece6-8307-4052-8510-ecdc24b81835.png)

**Comment by browaeysrobin** [comment]
Hi @mimisikai 

How did you define these niches? it seems like you put the same sender cell types in each niche. That's not going to work of course in the Differential NicheNet pipeline.

**Comment by mimisikai** [comment]
> Hi @mimisikai
> 
> How did you define these niches? it seems like you put the same sender cell types in each niche. That's not going to work of course in the Differential NicheNet pipeline.

Yes. They're from the same senders. but shouldn't I expect differential L-R signaling in the different niches? Conceptionally, the same sender could transmit differential signals via different L-R to different receivers.

**Comment by browaeysrobin** [comment]
Dear @mimisikai 

Conceptually you are right. But this is then due to the different receptors in the different receiver cell types.

the logFC heatmap plots the logFC of each ligand in the sender of interest vs other senders. If your senders are exactly the same in both niches, the plots for each niche will look the same, since the underlying data is the same.

That does not mean that the final niche prioritization scores will be the same. Focus on these and maybe increase the prioritization weights of the receptor logFC and ligand activities since these are the factors relevant to you. DE in ligands is not relevant for you since you consider the same senders in each niche.

**Comment by mimisikai** [comment]
> Dear @mimisikai
> 
> Conceptually you are right. But this is then due to the different receptors in the different receiver cell types.
> 
> the logFC heatmap plots the logFC of each ligand in the sender of interest vs other senders. If your senders are exactly the same in both niches, the plots for each niche will look the same, since the underlying data is the same.
> 
> That does not mean that the final niche prioritization scores will be the same. Focus on these and maybe increase the prioritization weights of the receptor logFC and ligand activities since these are the factors relevant to you. DE in ligands is not relevant for you since you consider the same senders in each niche.

I agree, that totally makes sense. Scientifically, many investigators may intend to use NicheNet to explore the undiscovered cellular communication pattern. Our question is which cell types are involved in different niches. Paradoxically, this vignette asks which types of cells you want to include for discovering the given niches.

**Comment by browaeysrobin** [comment]
Dear @mimisikai 

Differential NicheNet's goal is to find which interactions are different between known niches. Its goal is not to infer which are the possible niches, even though this is indeed a question many people have.

I think the best way to infer the possible niches, is to perform several lab experiments with complementary spatial technologies - as demonstrated in the paper https://www.sciencedirect.com/science/article/pii/S0092867421014811. Use experiments to define the niches, use cell-cell communication tools like (Differential) NicheNet how communication is different between the niches. 

If you really want to infer possible niches based on dissociated single-cell data alone, one potential approach could be to try to find which cell types explain each other's gene expression the best. To get measures of how well a sender cell type might predict a gene expression program of interest, you can check out this vignette: https://github.com/saeyslab/nichenetr/blob/master/vignettes/target_prediction_evaluation_geneset.md
For the goal of inferring niches, you can take inspiration here, but will have to code a lot yourself still (and we will not support this further at the moment)
