### ISSUE TITLE
Error make_ligand_activity_target_exprs_plot

### ISSUE THREAD

**Issue by mimisikai** [saeyslab/nichenetr#167]
`> exprs_activity_target_plot = make_ligand_activity_target_exprs_plot(receiver_oi, prioritized_tbl_oi,  
                                                                    prioritization_tables$prioritization_tbl_ligand_receptor, 
                                                                    prioritization_tables$prioritization_tbl_ligand_target, 
                                                                     output$exprs_tbl_ligand,  output$exprs_tbl_target, 
                                                                     lfc_cutoff, ligand_target_matrix, 
                                                                     plot_legend = FALSE, heights = NULL, widths = NULL)
`
Return: 
Joining, by = c("ligand", "ligand_score")
Error in `mutate()`:
! Problem while computing `ligand_ordered = factor(ligand, ordered = T, levels = ordered_ligands$ligand)`.
Caused by error in `levels<-`:
! factor level [2] is duplicated

Could you please hit which part of the data I should check to troubleshoot this problem? Thanks.

**Comment by browaeysrobin** [comment]
Hi @mimisikai 
Can you reinstall nichenetr and check this?
