### ISSUE TITLE
Question for interpreting ligand activity

### ISSUE THREAD

**Issue by mimisikai** [saeyslab/nichenetr#168]
Hi, I tried the differential nichnet on my data. 
How do I understand "NCAM1" ligand is highly expressed in the B niche but the ligand activity is relatively low in B in comparison with A? Similarly, the ligand TNF is highly expressed in the B niche, but no such difference in ligand activity between A and B. Thanks. 
![Presentation1](https://user-images.githubusercontent.com/4881411/186998269-b83763c2-eb27-4185-bd44-b56d4f02e9e9.jpg)

**Comment by browaeysrobin** [comment]
Hi @mimisikai 

Ligand activity predictions are made purely on target gene enrichment and don't take into account the expression of the ligand.

A high activity of a ligand in niche A means that there is enrichment of predicted target genes of that ligand among the genes upregulated in niche A vs B. A high activity of a ligand in niche B means that there is enrichment of predicted target genes of that ligand among the genes upregulated in niche B vs A.

How can you interpret a result where the ligand is highly expressed in niche A, but has higher activity in niche B? 
*) the ligand might be involved in active downregulation of genes in niche A, causing higher expression of those in niche B, resulting in higher activity for that niche
*) ligand activity predictions are predictions based on target gene predictions. And predictions can be inaccurate.
