### ISSUE TITLE
Some questions about different methods

### ISSUE THREAD

**Issue by mimisikai** [saeyslab/nichenetr#169]
I’m sort of confused with conventional NicheNet analysis, Differential NicheNet analysis between niches of interest, and Differential NicheNet analysis between conditions of interest.

Can I say, if given multiple receivers in the conventional NicheNet analysis, it will find out the common L-R pairs among these receivers? 

For Differential NicheNet analysis between niches of interest, you articulated that “we are interested in identifying the niche-specific ligands important for the identity of each of these macrophage subtypes”.  I speculate this method is particularly aiming to identify different L-R pairs from given niches. Can I understand instead of setting condition_oi = "LCMV", condition_reference = "SS", herein, you just compare differential niches with each other? If I have additional conditions (like LCMV, SS), should I go with the “Differential NicheNet analysis between conditions of interest” vignette? 

For Differential NicheNet analysis between conditions of interest, can I understand this includes additional conditions (e.g., healthy vs disease) besides different niches? But the NicheNet per se utilizes the differential expression in receiver cells under conditions (LCMV vs SS) to distinguish the impacts from sender cells. If so, how can I understand this “analysis between conditions of interest” differs from the setting in the general analysis workflow (condition_oi = "LCMV", condition_reference = "SS") ? Can I try “Differential NicheNet” on the LCMV/SS samples?

**Comment by browaeysrobin** [comment]
Hi @mimisikai 

As explained in the vignettes of the conventional NicheNet analyses and Differential NicheNet analyses:

conventional NicheNet: ligands are prioritized based on enrichment of their predicted target genes in a receiver cell type of interest. Which ligands are looked at depends on your sender cells of interest. Typically you select ligands that are expressed by at least one of the senders and have at least one receptor expressed by the receiver cell type of interest. If you use conventional NicheNet to compare a condition of interest with steady-state, you will rank ligands based on whether their target genes are DE between the condition of interest vs the steady-state. You will NOT rank ligands based on their DE themselves.

Differential NicheNet: ligands are prioritized based on their DE between niches/conditions, the DE of their receptors between niches/conditions, and their ligand activity. Only this last element in the prioritization is the same between conventional and differential NicheNet analyses. 

To answer your specific questions:

> Can I say, if given multiple receivers in the conventional NicheNet analysis, it will find out the common L-R pairs among these receivers?

No.

> Can I understand instead of setting condition_oi = "LCMV", condition_reference = "SS", herein, you just compare differential niches with each other? 

Yes.

> If I have additional conditions (like LCMV, SS), should I go with the “Differential NicheNet analysis between conditions of interest” vignette?

If you want to include DE of ligands and receptors in your prioritization: yes. If not: no.

> For Differential NicheNet analysis between conditions of interest, can I understand this includes additional conditions (e.g., healthy vs disease) besides different niches?

Not necessarily. Conditions and niches can be considered to be equivalent here. Differential NicheNet between conditions will study differential cell-cell communication between conditions, for a group of cell types that are the same or overlapping between conditions. Differential NicheNet between niches will compare cell-cell communication between different niches, that each consist of different cell types.

> But the NicheNet per se utilizes the differential expression in receiver cells under conditions (LCMV vs SS) to distinguish the impacts from sender cells. If so, how can I understand this “analysis between conditions of interest” differs from the setting in the general analysis workflow (condition_oi = "LCMV", condition_reference = "SS") ? 

See explanation above.

> Can I try “Differential NicheNet” on the LCMV/SS samples?

Yes. Interpretation of end results will just be different as explained above.
