### ISSUE TITLE
Differential nichenet Ligand-targets 

### ISSUE THREAD

**Issue by ejc043** [saeyslab/nichenetr#170]
Thank you for the wonderful package! 
From what I understand, the workflow of ranking putative ligands is to rank ligands based on how predictive they are for downstream genes. 
However sometimes for differential nichenet I've observed that although we have multiple high ranked ligand-receptor pairs, there are no ligand-target pairs that share the same ligand-receptors. Is this because only ligands are ranked by DEG and not the receptors as well?

**Comment by browaeysrobin** [comment]
Hi @ejc043 

> From what I understand, the workflow of ranking putative ligands is to rank ligands based on how predictive they are for downstream genes.

This is indeed true for the basic NicheNet workflow.

> However sometimes for differential nichenet I've observed that although we have multiple high ranked ligand-receptor pairs, there are no ligand-target pairs that share the same ligand-receptors. 

I'm sorry but I don't understand your question. Can you clarify what you mean with "there are no ligand-target pairs that share the same ligand-receptors" ?

To answer this question:

> Is this because only ligands are ranked by DEG and not the receptors as well?

Have a look at the vignette and the prioritization weights. There you can see that we also rank ligand-receptor pairs based on DE of the receptor. But the default weight is here lower, meaning it will have less influence than DE of the ligand. If wanted, you can change these weights.
