### ISSUE TITLE
DotPlot give a NA features in summary visualizations step

### ISSUE THREAD

**Issue by mimisikai** [saeyslab/nichenetr#171]
I ran this code and get this plot
> DotPlot(seuratObj %>% subset(CellType %in% sender_celltypes), features = order_ligands_adapted, cols = "RdYlBu")
Warning: Could not find DLL1 in the default search locations, found in RNA assay instead
Warning: Could not find LGALS3 in the default search locations, found in RNA assay instead
Warning: Could not find TNFSF12 in the default search locations, found in RNA assay instead
Warning: Could not find FGF2 in the default search locations, found in RNA assay instead
Warning: Could not find HMGB1 in the default search locations, found in RNA assay instead
Warning: Could not find HGF in the default search locations, found in RNA assay instead
Warning: Could not find SELPLG in the default search locations, found in RNA assay instead
Warning: Could not find ADAM17 in the default search locations, found in RNA assay instead
Warning: Could not find ANXA1 in the default search locations, found in RNA assay instead
Warning: Could not find TGFB1 in the default search locations, found in RNA assay instead
Warning: Could not find POMC in the default search locations, found in RNA assay instead

The far-right gene is "NA", but I check the order_ligands_adapted gene list doesn't have any NA. These color dots also are different. They seem to have multiple rings instead of a solid dot.  

![Screen Shot 2022-09-01 at 3 38 34 PM](https://user-images.githubusercontent.com/4881411/188024576-4b0c14c7-d44b-4797-bf2e-da42073a726f.png)

**Comment by browaeysrobin** [comment]
Hi @mimisikai 

I have never seen this. But it seems like all the other ligands in `order_ligands_adapted` are mapped onto each other. 
My guess would be that your DefaultAssay of your Seurat object does not contain expression information of all these ligands, or that something goes wrong with the subsetting of the cell type.

But this is actually more a Seurat::DotPlot than a NicheNet issue. If you cannot solve the problem yourself, you can ask them what the cause might be of getting this type of plot output.
