### ISSUE TITLE
LIANA results as LR db input

### ISSUE THREAD

**Issue by mimisikai** [saeyslab/nichenetr#172]
I note LIANA releases a vignette that integrates LIANA and NicheNet to explore the data. I wonder do you have any plan to combine the LIANA approach with your method. For instance, use LIANA outcome data as potential ligands in the predict_ligand_activities function.  But I don't clearly know if I should use LIANA results to replace lr_network et.al for downstream data interpretation. It would be super nice if you demonstrate this idea in a vignette.

**Comment by browaeysrobin** [comment]
Hi @mimisikai 

What would you expect/want to be different than the vignette currently presented by the developers of LIANA?

We don't have time to work on this the next couple of weeks/months but we are open to suggestions for improvements that we can implement later.

**Comment by mimisikai** [comment]
Actually, this is a technical question due to my unfamiliarity with the parameters of some functions. Can I say, use LIANA result to replace the lr_network in the entire vignette?  Or just use it in predict_ligand_activities(), calculate_niche_de() some particular functions. 
One more thing, LIANA generated data more or less is different from the LR pair sourced from lr_network. How to understand which one most likely presents the near reality condition.

**Comment by browaeysrobin** [comment]
Hi @mimisikai 

You could indeed use LIANA's output to replace the entire lr_network of NicheNet. 
You can also check the cell-cell communication tutorial from this github page https://github.com/saezlab/eccb2022_sc_funcomics - here you will find an example analysis of how to combine Liana with NicheNet
