### ISSUE TITLE
Could I only define one sender celltype in nitchenetr analysis?

### ISSUE THREAD

**Issue by peaceisking** [saeyslab/nichenetr#174]
Thank you for this wonderful package!

I have single cell data of two condotions (health and disease) and I have already used CellChat to find cell-cell interactions. The result of Cellchat told me that there was a strong interaction strength between CD14+ macrophage (sender) and neutrophils (receiver). And then I want to use nichenetr to identify specific changes in neutrophils caused by CD14+ macrophage between two conditions. My code is below:

nichenet_output <- nichenet_seuratobj_aggregate(seurat_obj = seurat_obj .integrated, 
                                               top_n_ligands = 20,
                                               receiver = "Neutrophil", 
                                               sender = "CD14+ macrophage",
                                               condition_colname = "condition", 
                                               condition_oi = "disease", 
                                               condition_reference = "health", 
                                               ligand_target_matrix = ligand_target_matrix, 
                                               lr_network = lr_network, 
                                               weighted_networks = weighted_networks, 
                                               organism = "mouse",
                                              assay_oi ="RNA",
                                              geneset = "up")

But I still hace questions:
1. I don't know it is right or not to use cellchat to find strong interaction strength between two cell-types at first, and then used the result to determine sender and receiver in nitchenet?
2. If I wanna know the changes of neutrophils in disease samples compared to healthy samples, is it a good idea to set geneset to "up", instead of all "DE" genes, just like we always used upregulated DEGs to do enrichment, instead of up- and down-regulated.

These questions warry me a lot, but they are quite important for me. I am new to bioinformatics analysis, hope for your answer!

**Comment by browaeysrobin** [comment]
Hi @peaceisking 

No worries, these are all very relevant questions!

1) This could indeed be a good approach to follow! Just know that other sender cell types might influence neutrophils as well, so including all cell types as potential senders might be an interesting follow-up analysis to check whether some predicted neutrophil-affecting ligands are also expressed by other cell types than CD14+ macrophages

2) Yes this can be a good idea, it might be easier for interpretation. However, you might miss some ligands that have mainly downregulatory effects
