### ISSUE TITLE
Differential Nichenet between niches/condition or default 

### ISSUE THREAD

**Issue by lengfei5** [saeyslab/nichenetr#176]
Hi there, 

I have just read your Differential Nichenet paper (https://www.sciencedirect.com/science/article/pii/S0092867421014811), 
and I am super excited to apply it with my own data.
 
But I would like to ask a couple of questions to clarify something still unclear to me. 

Let me explain first briefly our data and context.

We have paired scRNA-seq data and Visium data of heart injury;
we are mainly interested in the cell-cell communication in the border zone (BZ), next to the heart injury zone. 

With clustering + annotation of scRNA-seq data, we got the coarse cell types and subtypes. 
By leveraging the cell type deconvolution of Visium data, we identified BZ-specific subpoputions:
BZ-specific fibroblast(FB_BZ), 
macrophage (MP_BZ) 
cardiomyoctye (CM_BZ), 

which are subpopulations of fibroblast (FB), marcrophage(MP) and cardiomyocyte(CM) from our scRNA-seq data.

Therefore, here we have used the spatial information to define the niche of BZ.

So far, I see a two options to continue:

1) Run the default Nichenet by specifying sender and receiver cells, and geneset of interest will be defined by the comparison between BZ-specific and non-BZ cell populations.

2) Apply Differential Nichenet by defining two niches:
  one with FB_BZ, MP_BZ, CM_BZ
  the other with FB_nonBZ, MP_noBZ, CM_noBZ (the same cell types not in BZ). 

  because I indeed want to prioritize the ligands and receptors that are more highly expressed in BZ compared with non-BZ. 

So we would like to ask:

Q1) Which procedure seems to be better between those above two ?

Q2) Given the three cell types, FB_BZ, MP_BZ and CM_BZ, 
I have to enumerate each of those three as receiver cells and with the rest as sender cells, because we don't have any prior knowledge. 
in this case, should I make a for loop to do it, because I saw in your example, for the niche definition, only one cell types as receiver cells. Or is there easy way to do it ?

Apologize for the probably unimportant details,and your input will be extremely valuable.
Thank you .

Best,
Jingkui

**Comment by browaeysrobin** [comment]
Hi @lengfei5 

Both analyses can be applied to tackle your question. If you indeed want to prioritize the ligands and receptors that are more highly expressed in BZ compared with non-BZ, then the Differential NicheNet pipeline might be better for you. The default NicheNet pipeline will not consider ligand-receptor DE in the prioritization, only differential ligand activity. Differential NicheNet will consider both expression and activity, and you can change the prioritization weights of these factors to your wishes.

For your second question, you indeed have to run one (Differential) NicheNet analysis per receiver cell type. Whether that's in a for loop or a different script depends on your preferences.

**Comment by lengfei5** [comment]
Many thanks @browaeysrobin for your help. 
Really appreciate it. 

Best,
Jingkui

**Comment by lengfei5** [comment]
Dear @browaeysrobin , 

I got another question, probably asked by others.
Does it make sense to specify the same cell types as sender and receiver, trying to identify the ligands involved in the self-activation of the single cell type ?

Thanks.
Best

**Comment by lengfei5** [comment]
Hi again, 

I also would like to know how to change the default prioritization weights to give more weights to the ligand activity. 

As you explained, the default prioritization weights tened to give more high-DE (ligands) and low activity hits. 
How can I change the parameters of prioritization table to take more into account the ligand activity.

Many thanks.

**Comment by browaeysrobin** [comment]
> Dear @browaeysrobin ,
> 
> I got another question, probably asked by others. Does it make sense to specify the same cell types as sender and receiver, trying to identify the ligands involved in the self-activation of the single cell type ?
> 
> Thanks. Best

Yes, that can make sense indeed

**Comment by lengfei5** [comment]
Thank you so much for the quick answer. 
To make sure I understand correctly, 
scaled_ligand_score = 5; scaled_activity_normalized = 1; this will consider more weights on ligand DE than ligand activity.

scaled_ligand_score = 1; scaled_activity_normalized = 5; this will consider more weights on ligand activity. This will be more close to the default NicheNet. 

right ?

Thanks again.

**Comment by browaeysrobin** [comment]
Indeed!

**Comment by lengfei5** [comment]
many thanks and appreciate your help.

Best,
