### ISSUE TITLE
About the function predict_ligand_activities

### ISSUE THREAD

**Issue by mugpeng** [saeyslab/nichenetr#177]
Hello, 

It's a nice work of nichenet for considering not only ligand-receptor interactions but also 
relevant signaling paths. But I am facing some problems of `predict_ligand_activities` function when I am mimicking an article `Single-Cell Transcriptomic Analysis Reveals the Crosstalk Propensity Between the Tumor Intermediate State and the CD8+ T Exhausted State to be Associated with Clinical Benefits in Melanoma`. 
[Single-Cell Transcriptomic Analysis Reveals the Crosstalk Propensity Between the Tumor Intermediate State and the CD8+ T Exhausted State to be Associated with Clinical Benefits in Melanoma - PubMed](https://pubmed.ncbi.nlm.nih.gov/35903095/)

The author described:
> we applied NicheNet to predict ligand activities in each signal receiver cell by the predict_ligand_activities function in default parameters... For receiver cells, we identified state-related ligands whose predicted activities were significantly correlated with the average expression of cell state-specific signature (Pearson correlation test, FDR < 0.05).

And it seems that they got the predicted activities for all cells:
![image](https://user-images.githubusercontent.com/52995448/196849773-952c2c46-093c-48d8-8142-9dd6e9cfcec2.png)

But I notice the output of `predict_ligand_activities` is the pearson correlation between ligand and target. 

I didn't find any functions that can provide the ligand activity for each cells in the tutorial or R helps. 

Did I miss anything, or are there any methods can produce the above plots.

Thanks a lot.

Peng

**Comment by browaeysrobin** [comment]
HI @mugpeng 

I guess they based their analysis on this vignette:https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_activity_single_cell.md

**Comment by mugpeng** [comment]
Thanks, :)
