### ISSUE TITLE
Ligand-receptor-target gene expression interpret 

### ISSUE THREAD

**Issue by adesalegn** [saeyslab/nichenetr#178]
Dear nichenetr /@browaeysrobin 

Just wondering confused about how to interpret the **top ligand genes scored by the person correlation and the ligand-target regulatory potential score.** As you can see in the attached pdf, the top first ligand is **COL4A1**, but its target regulatory potential is pretty much low compared to the 2nd, 3rd, and even compared to the last ligand, which is **BMP6**. So why, then, is **COL4A1** at the top while its target regulatory potential score is low?  Let me know if my question is not clear.

Best,
Amare 
[ligend-receptor-target.pdf](https://github.com/saeyslab/nichenetr/files/9900215/ligend-receptor-target.pdf)

**Comment by browaeysrobin** [comment]
https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#if-i-look-at-the-combined-ligand-activity-target-heatmap-i-see-that-some-ligands-seem-to-have-higher-activity-but-less-target-genes-than-other-ligands-how-is-this-possible-if-the-ligand-activity-is-based-on-the-observed-target-genes-in-the-gene-set-of-interest
