### ISSUE TITLE
Issue matrix ligand-receptor network inference for top-ranked ligands

### ISSUE THREAD

**Issue by bilbaop** [saeyslab/nichenetr#180]
Hi,

I am trying to conduct the follow-up analysis 1 which is detailed in the vignette "NicheNet’s ligand activity analysis on a gene set of interest: predict active ligands and their target genes". 

For that, I constructed the ligand-target model from unoptimized data source weights as specified using the following code:

weighted_networks = construct_weighted_networks(lr_network = lr_network, sig_network = sig_network, gr_network = gr_network, source_weights_df = source_weights_df)
weighted_networks = apply_hub_corrections(weighted_networks = weighted_networks, lr_sig_hub = hyperparameter_list$lr_sig_hub, gr_hub = hyperparameter_list$gr_hub)`

However, the moment that I try to convert the matrix using:

lr_network_top_matrix = lr_network_top_df %>% select(-to) %>% as.matrix() %>% magrittr::set_rownames(lr_network_top_df$to)

I have this error:

Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'as.matrix': unable to find an inherited method for function 'select' for signature '"tbl_df"'

I have installed the magrittr package and everything that is required. Could you please let me know what is wrong with the code?

Thank you very much for your time!

**Comment by browaeysrobin** [comment]
Hi @bilbaop 

The problem is likely that you are using other packages that use the `select`. You can fix this this by changing select to `dplyr::select` or by loading in the other packages before tidyverse and nichenetr.
