### ISSUE TITLE
Differential expression SCT - issue #163 follow up

### ISSUE THREAD

**Issue by anaccsilva** [saeyslab/nichenetr#184]
Hello, 
I run PrepSCTFindMarkers() function before runing NicheNet for Seurat object. 
According to Seurat developers, we can't rerun PrepSCTFindmarkers more than once. So, if I've already run this code before, how should I proceed without running it again?
Considering that I am following this vignette [(For](https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md), what should I do in this part of the code?
DE_sender = calculate_niche_de(seurat_obj = seurat_obj %>% subset(features = lr_network$ligand %>% intersect(rownames(seurat_obj))), niches = niches, type = "sender", assay_oi = assay_oi) # only ligands important for sender cell types

It gives me the following error: 
"Error in FindMarkers.SCTAssay(object = data.use, slot = slot, cells.1 = cells$cells.1,  : 
  Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`."
I don't know exactly where thr "FindMarkers()" function is in this code, otherwise I would change and add their suggestion: "recorrect_umi = FALSE"

I appreciate your help.
 
Thank you,
Ana

**Comment by csangara** [comment]
Hi, sorry for the late reply.

Not sure if you are still interested in running the analysis, but in case you are - it seems you are running the Differential NicheNet pipeline? The `calculate_niche_de` function is inside `R/differential_nichenet.R`. From there, you can look for FindMarkers() and add that argument yourself, but this might be a bit complicated...is it not possible to start from the raw counts again when you run NicheNet?
