### ISSUE TITLE
Get_expressed_genes error

### ISSUE THREAD

**Issue by vwtlin** [saeyslab/nichenetr#185]
Hi NicheNet team,

Thanks very much for this amazing tool. I am applying this tool to a homeostatic condition. As suggested by the FAQ, I need to set all genes in the ligand-target matrix as background expressed genes. However, in this way, all the genes may not be expressed as the rule that a gene should be expressed in 10% of cells could not apply. 

Therefore I am thinking to use `get_expressed_genes` function to obtain all the genes expressed by all the cell types. 

Some cell types could only have one cell and `get_expressed_genes` returned errors as below on these cell types. 
Error in apply(., 1, function(x) { : dim(X) must have a positive length

For cell types with more than two cells, this function works fine. Could you comment if it is necessary to obtain the background genes using `get_expressed_genes` ?

Cheers,
Weitao

**Comment by csangara** [comment]
Hi Weitao, sorry for the late reply, and thanks for using our tool!

We would not really recommend using NicheNet on your dataset in this case, as it is steady state and some cell types has very few cells. But if you wish to proceed with the analysis, it is not necessary to use the `get_expressed_genes` function. As you may have seen in our `ligand_activity_geneset` vignette, we recommend users to define expressed genes in the way that they consider to be most appropriate for their dataset (e.g., by using a cutoff value). So, it is not a 'rule' that expressed genes are genes should be expressed in 10% of the cells.
