### ISSUE TITLE
DeSeq2 Object

### ISSUE THREAD

**Issue by macelik** [saeyslab/nichenetr#186]
Hello, I was wondering if there is anyway to run NicheNet on DeSeq2 object? If no, what would you advice?

**Comment by csangara** [comment]
Hi,

If you already have a gene set of interest (e.g., from differentially expressed genes), you could simply extract the count matrix and metadata information from the DeSeq2 object and follow the `ligand_activity_geneset` vignette.
 
If you would like to use the Seurat object vignette, you can convert the DeSeq2 object to a Seurat object with something like this:
```
library(Seurat)
seurat_object <- CreateSeuratObject(counts(DEseq_obj), meta.data = data.frame(colData(DEseq_obj)))
```
You would then have to set the identity of the Seurat object appropriately when using the `nichenetr::get_expressed_genes` and `Seurat::FindMarkers` functions.
