### ISSUE TITLE
Interpretation potential scores

### ISSUE THREAD

**Issue by joan-yanqiong** [saeyslab/nichenetr#188]
Hi, I saw in the paper the heatmaps (and also in the vignettes) for the potential scores, but it is still a bit unclear to me what would be considered a low or high score. Maybe I missed it, but I didn't read an explanation in the paper. For example a regulatory potential of 0.004, what does that mean? 

And for the prior interaction potentials is the score on a scale of 0-1? 

Thanks in advance for your time!

**Comment by csangara** [comment]
Hi, sorry for the late reply.

You can check out #78 and #92 for some more explanation.

The short version is: it's difficult to say what is a low or high score. Indeed, theoretically they can range from 0-1, but we observe in our ligand-target matrix that the values only go up as high as 0.07 for NicheNet v1, and 0.34 for v2. And another important factor is  you can't compare scores between ligands - only within a ligand. So if the scores of ligandX-targetA = 0.1 and ligandY-targetA = 0.2, you can't really say with certainty that ligandY has more potential to regulate targetA than ligandX. But if the score of ligandY-targetA > ligandY-targetB, you can say that ligandY has more potential to regulate targetA than targetB.
