### ISSUE TITLE
How to use this with Bulk RNA seq data from two different cell types?

### ISSUE THREAD

**Issue by BhavanaNayer** [saeyslab/nichenetr#189]
Hi, Thank you for this wonderful tool. I have tried to explore this a bit with single cell data from tissues that contain multiple cell types, but now I am interested in analysing two separate bulk RNA sequencing datasets we have: (1) bulk RNA seq of a purified sorted population of T cells, and (2) bulk RNA seq of a purified sorted population of macrophages. 
I want to understand if there are ligands expressed by these T cells that can act on macrophage receptors, and then potentially show them in a Circos plot. So the sender cell type is my T cell dataset, and the receiver cell type is the macrophage dataset. Each of these individual T cell and macrophage datasets can be used to obtain differentially expressed genes between a steady state and a treated condition. So I have the DEGs in T cells upon treatment compared to untreated, and then DEGs in macrophages upon a related treatment, compared to untreated. Now I want to know whether the ligand gene expression in the T cells upon treatment, can be matched with receptor gene expression in the macrophages upon the related treatment. 
Is it possible to set this up with NicheNet? I have only started doing Bioinformatics analysis a few months ago and I'm still learning slowly so any guidance on how to use this tool for this particular scenario would be extremely helpful. Thank you so much in advance!

**Comment by csangara** [comment]
@BhavanaNayer Hi, thanks for your interest in our tool, and sorry for the late reply.

NicheNet can be used for this type of data, but I don't know if it's the most appropriate tool if you are just want to match ligand expression and receptor expression together.

NicheNet would ideally be used in case the change in macrophages after treatment was caused by cell-cell communication with T cells. If that is the case, you can use the DEGs of macrophages before and after treatment as your gene set of interest. Then, you can follow the workflow of the [`seurat_steps`](https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md) vignette and adapt it for bulk data. For example, to filter for expressed genes, instead of using our `get_expressed_genes` function, you can use the `filterByExpr` function from `edgeR` (you might have to adapt some of the parameters if too many genes are filtered out). From that you should be able to get your potential ligands and background expressed genes.

Hope this helps!

**Comment by csangara** [comment]
@LuShuYangMing The ligand-target tables only contain genes that are in your gene set of interest, so if your DE genes are different between A vs B and C vs D, these resulting targets in the dataframe will also be different. The ligand-receptor tables are will be the same across groups if you if you calculated the expressed ligands and receptors on the entire dataset. Did you try subsetting the data to only contain cells from a certain group when getting the ligands and receptors?

**Comment by SergioRodLla** [comment]
Hello, 
I'm trying to follow the vignette `seurat_steps_prioritization.md` using two bulk RNA-seq data of sorted cells. I was wondering if in the case I want to use DEGs as my genes of interest to prioritize ligand-receptor pairs, could I do it by adapting the steps in this vignette or should I just follow the steps of the basic one (`seurat_steps.md`) by just setting the expressed genes in the sender and receiver cell as my DEGs?
Thank you in advance!

**Comment by csangara** [comment]
Hi @SergioRodLla,
The beginning steps of both vignettes are actually the same, the prioritization vignettes just contain a few extra steps at the end. I think starting off with the `seurat_steps.md` vignette is a good idea, but I don't really understand what you mean by setting the expressed genes as your DEGs. Which step are you referring to?

**Comment by SergioRodLla** [comment]
Hi @csangara,
Thanks for the reply. I meant that at step 2 of the `seurat_steps.md` vignette I am using the DEGs from my bulk RNA-seq experiment as `geneset_oi`, doing like this to get the gene IDs that are included in the `ligand_target_matrix`.
```
geneset_oi <- bulk-rna_DEGs_reciever_diet1VSdiet2.df %>% # select condition of interest
  filter(geneID %in% rownames(ligand_target_matrix)) %>%
  pull(geneID)
```
`bulk-rna_DEGs_reciever_diet1VSdiet2.df` is a dataframe that contains the DEGs in the potentially receiver cell-type in my condition of interest (2 types of diet) that I want to test for interactions. 
I hope this helps,
Sergio

**Comment by csangara** [comment]
Yes, that makes sense.

**Comment by Shanthosh29** [comment]
Hello there, 

I have a doubt on the use of the SeuratObject.
Is it supposed to be used only for scRNA-seq datasets? or we are obliged to use the package?

Btw, I am trying to observe any cell cell interactions on my bulkRNA seq data, which has values of DEGs consisting of up and down-regulated genes.

Could you please guide me on how to proceed?

Thanking you in advance for your reply.

**Comment by Shanthosh29** [comment]
# Use lapply to get the expressed genes of every sender cell type separately here
list_expressed_genes_sender <- sender_celltypes %>% unique() %>% lapply(get_expressed_genes, seuratObj, 0.05)
expressed_genes_sender <- list_expressed_genes_sender %>% unlist() %>% unique()
Erreur dans get_expressed_genes.Seurat(X[[i]], ...) : 
  One or more provided cell clusters is not part of the 'Idents' of your Seurat object
