### ISSUE TITLE
Replacing Gene regulatory network

### ISSUE THREAD

**Issue by anthonybejjani** [saeyslab/nichenetr#194]
Hello,

I am interested in running NicheNet but I would like to replace the GRN used with a custom one. I can't find a vignette or information anywhere regarding how to do this. Is there a function for it? Thank you for your help!

**Comment by anthonybejjani** [comment]
Hello,

I am interested in running NicheNet but I would like to replace the GRN used with a custom one. I can't find a vignette or information anywhere regarding how to do this. Is there a function for it? Thank you for your help!

**Comment by csangara** [comment]
Hi, sorry for the late reply.

Have you checked out the [`model_construction`](https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md) vignette? You can use the `construct_weighted_networks` function with `gr_network` as your own.

Hope this helps!
