### ISSUE TITLE
Requesting Guidance on Obtaining Log2FC Scores for Individual Ligand-Receptor Pairs

### ISSUE THREAD

**Issue by macelik** [saeyslab/nichenetr#196]
Hello,

I am currently working on running NicheNet on scRNA data and have been following the step-by-step analysis provided in the NicheNet GitHub repository (https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md). My goal is to obtain differentially expressed ligand-receptor interactions. I have divided my workflow into two parts:

1. Differential expression analysis: I perform a differential expression analysis for each cell type within a Seurat object, comparing the conditions of interest (in this case, "AML" and "healthy"). The output of this analysis is a set of differential expression tables, with one table for each cell type.

2. Ligand activity prediction: I aim to predict ligand activities based on the differentially expressed genes, I adapted the methods provided by NicheNet. This step is performed iteratively for each cell type and each sample. I start by identifying the intersection between the set of differentially expressed genes and the set of expressed genes for the receiver cell type in each sample. Since the differential expression calculation cannot be separated by sample, I aim to obtain sample-specific DE genes that are then passed to the `predict_ligand_activity` function as `geneset_oi`. Additionally, I collect the expressed genes for the receiver cell type in the corresponding sample and pass them as the `expressed_genes` parameter. After obtaining the `ligand_activities`, I filter the weighted network to retain the ligand-receptor (LR) pairs where the "from" nodes correspond to potential ligands and the "to" nodes correspond to expressed receptors. This filtering step produces a list of LR pairs with weighted network scores.

However, I am interested in obtaining log2FC scores for each individual ligand and receptor pair separately. I would greatly appreciate any suggestions or guidance on how to accomplish this.

Thank you for your assistance.

**Comment by csangara** [comment]
Hi,

Have you looked into our [MultiNichenet](https://github.com/saeyslab/multinichenetr) extension? The [pairwise MIS-C analysis](https://github.com/saeyslab/multinichenetr/blob/main/vignettes/pairwise_analysis_MISC.md) sounds quite similar to what you might want.
