### ISSUE TITLE
Scaled ligand activity and scales for plots 

### ISSUE THREAD

**Issue by mxs1637** [saeyslab/nichenetr#203]
What does scaled ligand activity show and what is different about it compared to ligand activity?
Also why is there no scales on these plots along with the ligand expression, and predicted target genes plots shown in the exprs_activity_target_plot along with its top 20 version? Is there a way to get the scales necessary for them , if so how?

**Comment by mxs1637** [comment]
This is for the Differential NicheNet analysis between conditions of interest tutorial

**Comment by mxs1637** [comment]
just for clarification i mean the colour scales for the exprs_activity_target_plot

**Comment by csangara** [comment]
As in #149, the scaled ligand activity is the z-score normalization on the ligand activity values (= AUPR values in NicheNet v2)

The legend for the plots can be accessed using `exprs_activity_target_plot$legends`. There is also an option in `make_ligand_activity_target_exprs_plot` to have `plot_legend=TRUE`.
