### ISSUE TITLE
Ligand treatment datasets (rather than just logFC)

### ISSUE THREAD

**Issue by j-bac** [saeyslab/nichenetr#205]
expression_settings.rds on [https://zenodo.org/record/3260758](https://zenodo.org/record/3260758) and [https://zenodo.org/record/8010790](https://zenodo.org/record/8010790/) contains the list of logFC genes. Would you have a file to download with all expression profiles by any chance ? Many thanks

**Comment by csangara** [comment]
Yes, you can find it in this link https://zenodo.org/record/3462199 which contains all the code and data to reproduce the analyses of the NicheNet paper. It's in the `evaluation_final.zip` file, under `ligand_treatment_datasets/data`.

**Comment by j-bac** [comment]
thanks a lot! Are data and code for CytoSig datasets also available somewhere on zenodo ?

**Comment by csangara** [comment]
No problem :) Yes, at https://zenodo.org/record/8016880 in `NicheNet_V2.zip`, under `CytoSig/`.
