### ISSUE TITLE
use scaled ligand activity or ligand activity to find condition-related ligand?

### ISSUE THREAD

**Issue by sadiexiaoyu** [saeyslab/nichenetr#209]
Hi,

Thank you for the cool software!
I have a question regarding to whether should use **scaled** ligand activity or ligand activity to find condition-related ligand ?
It seems that **scaled** ligand activity is a transformed result and is better for comparisons across different conditions, as seen in https://github.com/saeyslab/nichenetr/issues/149.
But from the vignette of Differential Nichenetr https://github.com/saeyslab/nichenetr/blob/master/vignettes/differential_nichenet.md, the output example showed super low value of scaled-ligand activity, but high ligand activity as follows:
<img width="1239" alt="Screen Shot 2023-07-19 at 16 06 33" src="https://github.com/saeyslab/nichenetr/assets/16802530/17d0d3d4-8278-4960-bf82-fe771970f3f2">

And the vignette wrote that _On this plot, we can see that some strongly DE ligand-receptor pairs in the KC niche, have also high scaled ligand activity on KCs - making them strong predictions for further validation._ 
_important: ligand-receptor pairs with both high differential expression and ligand activity (=target gene enrichment) are very interesting predictions as key regulators of your intercellular communication process of interest !_

So, should we only care about ligand activity, and ignore the low value of scaled ligand activity?

**Comment by csangara** [comment]
I've added an extra parameter in `make_ligand_activity_target_exprs_plot`, namely by setting `scaled_ligand_activity_limits = "IQR"`, the range of values considered for the color scale are [Q1-1.5\*IQR, Q3+1.5\*IQR] as in boxplots. Outliers will therefore have their colors squished to the min or max color. The visualization looks better now:

![image](https://github.com/saeyslab/nichenetr/assets/17024850/391d9e63-f43b-49f1-9fde-b37e12067b7b)
