### ISSUE TITLE
Prioritization: prior_table

### ISSUE THREAD

**Issue by nea-k** [saeyslab/nichenetr#210]
Hi! Are the lfc_ligand and lfc_receptor values in the prior_table of the prioritization vignette based on differences between cell types or conditions? I'm trying to analyze the differences between controls and our condition of interest but having some trouble with understanding how to best visualize that. If I have understood correctly, the prioritized ligand-receptor pairs are differentially expressed between the conditions, but I would like to have some extra quantitative information on how much of a difference there really is. I would appreciate any tips on this also!

**Comment by csangara** [comment]
Hi,

The `lfc_ligand` and `lfc_receptor` columns are based on the differences between cell types within your condition of interest. This is equivalent to subsetting your Seurat object to only the condition of interest and running `Seurat::FindAllMarkers`.

The columns that refer to differential expression between conditions are those with the `_group` suffix, e.g., `lfc_ligand_group` and `lfc_receptor_group`. These are celltype agnostic: they are calculated by using `Seurat::FindMarkers` between two conditions across all cell types.

(I see now that it can be confusing, so I will update the documentation of `generate_prioritization_tables` to state this more clearly in the output value.)

To prioritize ligand-receptor pairs, these columns are used (after scaling), along with the average expression of the ligand and receptors and of course, the ligand activity analysis in the original NicheNet. 

I'm not sure I totally understand your final question about wanting quantitative information (so please feel free to clarify further if my answer is off-base), but could using the `scaled_*` columns help with comparing these values relatively?
