### ISSUE TITLE
Is differential grouping a must?

### ISSUE THREAD

**Issue by pratibha-bioinfo** [saeyslab/nichenetr#212]
Hi team,

I'm a first time user of GitHub so apologies for not following the correct syntax of posting a query. I have been using this amazing software to find CCC but my doubt is every article I read they all have two groups for comparison for affected cell types. My experiment has been performed to characterise how one cell type gets affected by signals from nearby cell types in single-cell RNA seq data where I do not have any control or treatment groups. All samples belong to the same group. 

Can Nichenet be still used in this case as I see the differential expression gene set is a crucial step for moving forward?

Thank you,
Pratibha

**Comment by csangara** [comment]
Hi Pratibha,

[This answer](https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#when-going-to-the-vignettes-i-see-you-require-differential-expression-between-two-conditions-what-if-i-only-have-steady-state-data-and-want-to-use-nichenet-cant-nichenet-be-used-to-find-ligand-receptor-pairs-in-steady-state) in the FAQ may shed some light on the issue.

In short: it is possible to use NicheNet without having multiple groups, but this is highly dependent on your biological question and dataset. Therefore we cannot provide you with ready-to-use code in this scenario.

Best,
Chananchida

**Comment by pratibha-bioinfo** [comment]
Hi Chananchida,

Thank you for your response!
