### ISSUE TITLE
ligand should be in ligand_target_matrix

### ISSUE THREAD

**Issue by johjoon** [saeyslab/nichenetr#213]
Hello，
Following the [tutorial](https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_activity_geneset.md) or use my own data, I came across a same erro message:

`ligand_activities = predict_ligand_activities(geneset = geneset_oi, background_expressed_genes = background_expressed_genes, ligand_target_matrix = ligand_target_matrix, potential_ligands = potential_ligands)`

And the erro message is :

Error in evaluate_target_prediction(setting, ligand_target_matrix, ligands_position) : 
  ligand should be in ligand_target_matrix

I failed to solve this problem and have no idea about this.

Thanks

**Comment by csangara** [comment]
Hi,

This means that there is no intersection between `potential_ligands` and `colnames(ligand_target_matrix)`. Can you check whether your `potential_ligands` vector is empty, and whether you are using the correct ligand target matrix for your data (e.g., mouse model for mouse data)?
