### ISSUE TITLE
Error in prepare_ligand_target_visualization function

### ISSUE THREAD

**Issue by mdrezaulislam** [saeyslab/nichenetr#215]
Thank you for this nice tool. I was attempting to run the tutorial and getting error in the step 

active_ligand_target_links = prepare_ligand_target_visualization(ligand_target_df = active_ligand_target_links_df, ligand_target_matrix = ligand_target_matrix, cutoff = 0.33)

the error message is "Error in hclust(distoi, method = "ward.D2") : Invalid clustering method"

Would appreciate if you guide me how to resolve this.

**Comment by csangara** [comment]
Hi, can you give me the output of `sessionInfo()` when you run into this error?
