### ISSUE TITLE
Mistake in process_table_to_ic for DE_table

### ISSUE THREAD

**Issue by sisaberg** [saeyslab/nichenetr#216]
Hello,

I just started working with NicheNet and in found something in the process_table_to_ic function where I am unsure if it is a mistake:

In line 61 to 63
  sender_receiver_table <- sender_receiver_table %>% mutate(ligand_receptor_avg = case_when(table_type == 
                                                                          "expression" ~ avg_ligand * avg_receptor, grepl("DE$", 
                                                                   table_type) ~ (avg_ligand + avg_ligand)/2)) %>% arrange(-ligand_receptor_avg) %>% 

Should it not say (avg_ligand + avg_receptor)/2)? Otherwise the ligand_receptor_lfc_avg will just be the same as lfc_ligand.
If this is not a mistake, could you explain why this line of the code is necessary?

Thank you for the great package!

**Comment by csangara** [comment]
Hi @sisaberg,

You're right, there is a mistake there...sorry about that. Feel free to change it to `avg_receptor` for now - I will update the package with a patch fix for this and other issues ASAP.

Thanks!
