### ISSUE TITLE
manually select ligand target pair

### ISSUE THREAD

**Issue by yaolutian** [saeyslab/nichenetr#22]
Thanks for this excellent tool, I am following the seurat wrapper, I want to know if there is a way to select part of the ligand target to show in heatmap in a simple way?

Thanks!

**Comment by browaeysrobin** [comment]
Hi @yaolutian 

`nichenet_output$ligand_target_matrix` contains the output ligand-target matrix. You can manually subset ligands and targets here, and then give this subset ligand-target matrix as input for a heatmap visualization tool yourself. You can do this with a tool you want, or look at how we do that in the vignettes https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md and https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_activity_geneset.md.
