### ISSUE TITLE
confused about the DE_table results

### ISSUE THREAD

**Issue by sadiexiaoyu** [saeyslab/nichenetr#220]
I am using the new vignettes **Perform NicheNet analysis with prioritization**

When I run 
DE_table <- calculate_de(seuratObj, celltype_colname = "xxx",
                         condition_colname = "xxx", condition_oi = "condition that I am interested in"
                         features = union(expressed_ligands, expressed_receptors))
the clusters that it calculated for DE genes is not the condition that I am interested in, instead, it seems to calculate the reference condition (because each condition has its specific cell type, so that I can differentiate which condition it calculated easily).

So I am confused about it, and hope helpful suggestions.
Thanks !

**Comment by csangara** [comment]
Hi,
I'm a little confused about your question, but I will try to answer how calculate_de works.
`calculate_de` subsets your Seurat object to only your condition of interest, and then uses `Seurat::FindAllMarkers` for all cell types. So you will get an output table with all cell types present in your condition of interest. And later on during the prioritization, ligands and receptors that are DE in a certain cell type will get a higher ranking.

If this is not clear, please feel free to ask more questions.

**Comment by sadiexiaoyu** [comment]
> Hi, I'm a little confused about your question, but I will try to answer how calculate_de works. `calculate_de` subsets your Seurat object to only your condition of interest, and then uses `Seurat::FindAllMarkers` for all cell types. So you will get an output table with all cell types present in your condition of interest. And later on during the prioritization, ligands and receptors that are DE in a certain cell type will get a higher ranking.
> 
> If this is not clear, please feel free to ask more questions.

Yes, I understand the principle. Just when I run it with setting condition_oi = "condition that I am interested in", the resulting table showed the DE genes among cell types in another condition, not the condition that I am interested in. 
I wonder maybe I can subset the condition of interest and FindAllMarkers using seurat to get the DE_table, and then use this DE_table in the following code in the vignette.

**Comment by csangara** [comment]
Hi, sorry for getting back to you so late.
You were right, there was a bug in `calculate_de` that I only found now. Can you update to v2.0.2 and see if the genes make more sense now?
Thanks again, I really appreciate your help with all these issues.
