### ISSUE TITLE
Error in DiagrammeR::render_graph

### ISSUE THREAD

**Issue by fangshansh** [saeyslab/nichenetr#228]
HI,
thank you for a great package and resource. 

I have some error in DiagrammeR::render_graph.

 I followed vignette-ligand_target_signaling_path.md

And I got those errors in below.

DiagrammeR::render_graph(graph_min_max, layout = "tree")
Error in viewer(index_html) :
  'browser' must be a non-empty character string

What is the reason for this? Looking forward to your reply.

Thanks.

**Comment by csangara** [comment]
Hi,

To determine whether this a NicheNet issue or a DiagrammeR issue, can you try running the first chunk of the [DiagrammeR tutorial](https://rich-iannone.github.io/DiagrammeR/)?

Specifically, this code:
```
library(DiagrammeR)
example_graph <-
  create_graph() %>%
  add_pa_graph(
    n = 50, m = 1,
    set_seed = 23
  ) %>%
  add_gnp_graph(
    n = 50, p = 1/100,
    set_seed = 23
  ) %>%
  join_node_attrs(df = get_betweenness(.)) %>%
  join_node_attrs(df = get_degree_total(.)) %>%
  colorize_node_attrs(
    node_attr_from = total_degree,
    node_attr_to = fillcolor,
    palette = "Greens",
    alpha = 90
  ) %>%
  rescale_node_attrs(
    node_attr_from = betweenness,
    to_lower_bound = 0.5,
    to_upper_bound = 1.0,
    node_attr_to = height
  ) %>%
  select_nodes_by_id(nodes = get_articulation_points(.)) %>%
  set_node_attrs_ws(node_attr = peripheries, value = 2) %>%
  set_node_attrs_ws(node_attr = penwidth, value = 3) %>%
  clear_selection() %>%
  set_node_attr_to_display(attr = NULL)

render_graph(example_graph, layout = "nicely")
```

If you get the same error, it might be better to post it as an issue in DiagrammeR instead.

**Comment by fangshansh** [comment]
Hi,
Thank you for your reply, I ran the first chunk of the [DiagrammeR tutorial](https://rich-iannone.github.io/DiagrammeR/) and got the same error, I have posted it as an issue in DiagrammeR.
