### ISSUE TITLE
About question in "Perform NicheNet analysis with prioritization" vignette

### ISSUE THREAD

**Issue by wang2034** [saeyslab/nichenetr#231]
Hi,
Thanks for developing this great tool.
I have a question in prioritization analysis. In line 234,  the R-script is "celltypes <- unique(seuratObj$celltype)"
Can any one who did this analysis before explain this code? What is the function of the variable "celltypes"? Thanks

**Comment by csangara** [comment]
Hi,
It seems the variable was left there from an earlier version of the vignette. It is indeed not necessary. I've now removed it, thanks for the catch!
