### ISSUE TITLE
get_exprs_avg produced error message

### ISSUE THREAD

**Issue by wang2034** [saeyslab/nichenetr#233]
Hello,
I am performing NicheNet_prioritization with SCTransformed-integrated data. My seurat object contains 4 conditions, and I selected 2 conditions for NicheNet_prioritization analysis. When I ran get_exprs_avg() function, I got error message:

Error in validObject(object = value) : 
  invalid class “SCTAssay” object: 1: all features in 'scale.data' must be present in 'data'
invalid class “SCTAssay” object: 2: 'meta.features' must have the same number of rows as 'data'
invalid class “SCTAssay” object: 3: all 'var.features' must be present in

**Comment by csangara** [comment]
Hi,

Are you using the latest version of NicheNet (v2.0.4)? If not, can you try and see if the error persists?
