### ISSUE TITLE
Trouble with get_prioritization_tables

### ISSUE THREAD

**Issue by pushpinder-bu** [saeyslab/nichenetr#234]
Hi,

I am following the below vignettes to do a differential nichenet between by 2 conditions of interest.
https://github.com/saeyslab/nichenetr/blob/master/vignettes/differential_nichenet_pEMT.md

I am running into below error when running get_prioritization_tables

> prioritization_tables = get_prioritization_tables(output, prioritizing_weights)
Error in eval(substitute(condition), .data, envir) : 
  object 'bonafide' not found

Can you suggest what happening here? I don't see making any bonafide object in the vignettes.

**Comment by csangara** [comment]
Hi,

Is it possible you're not using the latest version of NicheNet (v2.0.4)? Starting from v2, we removed the 'bonafide' option for a lot of functions.
