### ISSUE TITLE
I got trouble when running nichenet_seuratobj_aggregate()

### ISSUE THREAD

**Issue by fishskywd** [saeyslab/nichenetr#235]
nichenet_output = nichenet_seuratobj_aggregate(
  seurat_obj = sce, 
  receiver = "neu_0", 
  condition_colname = "group", condition_oi = "Disease", condition_reference = "Healthy", 
  sender = c("B cell","Endothelial", "Epithelial","Fibroblasts","Macrophage","Mast cell","neu_1","neu_2","neu_3","Plasma cells","T cell/NK"), 
  ligand_target_matrix = ligand_target_matrix,
  lr_network = lr_network,
  weighted_networks = weighted_networks)

This is the bug:
[1] "Read in and process NicheNet's networks"
[1] "Define expressed ligands and receptors in receiver and sender cells"
[1] "Perform DE analysis in receiver cell"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=03s  
[1] "Perform NicheNet ligand activity analysis"
[1] "Infer active target genes of the prioritized ligands"
[1] "Infer receptors of the prioritized ligands"
Error in if (length(sender) > 1 | (length(sender) == 1 & sender != "undefined")) { : 
  the condition has length > 1

**Comment by csangara** [comment]
Hi,

Which version of NicheNet are you running? I think this might be an old error that we fixed already. Can you try updating to the latest version?
