### ISSUE TITLE
ask questions about model constructing

### ISSUE THREAD

**Issue by xuansuyang** [saeyslab/nichenetr#236]
First of all, thank you very much for developing this tool. I have a few questions regarding the modeling process, and I'd like to ask you the following:

We use several databases such as lr_network and sig_network as input to obtain weighted networks. How are these weighted networks generated?
When predicting downstream targets for a given ligand to determine if a target is activated by an upstream ligand, what is the scoring criterion? Are there specific threshold values used for filtering?

**Comment by Eisuan** [comment]
Thank you for your inquiry and interest in NicheNet.

**NicheNet regulatory model construction:**

To score and rank ligand activity, NicheNet utilizes a ligand-target network, which is indeed the only network input required for the standard usage of the `predict_ligand_activities` function.

This ligand-target network is obtained via matrix multiplication of a ligand-regulator matrix and a regulator-target matrix, which represent the ligand-signaling network and the gene regulatory network (GRN) underlying NicheNet (https://www.nature.com/articles/s41592-019-0667-5/figures/3).

These two networks were modeled separately by integrating distinct data sources for the ligand-signaling and gene-regulatory networks respectively. The integrated networks were obtained via weighted aggregation of the different data sources. The weights assigned to each data source, as well as additional hyperparameters, were tuned via a multi-objective optimization procedure assessing the predictive performance of the model on gold standard datasets*. However, the ligand-target network was not retrieved by directly multiplying the weights of the ligand-signaling network by those of the gene regulatory network. Instead, the numerical values employed to leverage the ligand-signaling network information are signaling importance scores. These scores capture the signaling importance of each gene in the pathway downstream of each ligand in the context of the ligand-signaling network. The quantification of information flow propagation from ligands to the rest of the network was performed using personalized PageRank (PPR). This retrieved a measure that quantifies the importance of the gene *k* in the signaling pathway of the *i* ligand (PPRik). 

The final ligand-target network describing the regulatory potential of ligand *i* for the target gene *j* was computed by multiplying the PPRik by the weight of GRNkj, which represents evidence that gene *k* regulates the expression of target gene *j* based on the gene regulatory network.

**NicheNet standard ligand prioritization procedure:**

The standard procedure of ligand activity ranking is essentially an enrichment procedure. The  `predict_ligand_activities`  function requires to specification of two sets of genes for the receiver cells: a gene set of interest (GOI), which contains genes assumed to be the target of the cell communication process being studied, and a set of unrelated background genes expressed in the receivers. These two sets are then merged in the same named logical vector, in which the TRUE value is assigned for genes belonging to the GOI set. 

The function also requires as input a set of putative ligand genes for sender cells. Then, for each ligand *i,* the regulatory potential for each gene in the GOI or background set is extracted from the ligand-target matrix. This information allows for the computation of several ranking scores. In the vignette, our visualization for ligand prioritization employs the AUPR metric, which is computed for each ligand based on its vector of regulatory potential for receiver cells genes and the binary gene vector (TRUE for GOI). These two vectors are used as prediction and true class label input for ROC curve computation, which is then used for AUPR calculation. 

*Target gene and ligand activity prediction performance of the model were optimized on gold standard datasets. These consisted of microarray datasets assessing the in vitro transcriptional response before and after treatment with one or two protein ligands across different human and mouse cell types. Please refer to [https://www.nature.com/articles/s41592-019-0667-5](https://doi.org/10.1038/s41592-019-0667-5) for further details.

**Comment by xuansuyang** [comment]
Thank you for you reply.
