### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by rsggsr** [saeyslab/nichenetr#24]
I am wondering if could tell me how to solve this installation problem shown below. Thanks!

> error: Failed to install 'nichenetr' from GitHub:
  (warnings) cannot remove prior installation of package ‘reshape2’

And I also could not remove this package by remove.packages()

> remove.packages("reshape2")
Removing package from ‘C:/Users/Lin/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Error in find.package(pkgs, lib) : there is no package called ‘reshape2’

**Comment by browaeysrobin** [comment]
Hi @rsggsr 

This is probably a nichenetr-unrelated problem you have on your pc. Can you try to install other packages (from github) and check whether that works.  If it would seem to be a nichenetr-specific problem for you, could you give some more details about the what went wrong in the installation. For now I have not enough information to know where the problem might be for you.

About the removal of the reshape2 package, you should identify the correct path to that directory (now R searches for the default path, but your reshape2 package is not located there), and give it as input to the remove.packages function.

**Comment by rsggsr** [comment]
Hi @browaeysrobin ,

Sorry that's my bad. I get it done afterwards. 

But I got another question for you. I am playing with my processed Seurat object and mostly following the vignette for Seurat (Perform NicheNet analysis starting from a Seurat object: step-by-step analysis:vignette("seurat_steps", package="nichenetr")). But when I want to plot a circos plot using that tutorial I found it's not that easy to follow since it's a follow-up tutorial for the vignette (NicheNet’s ligand activity analysis on a gene set of interest: predict active ligands and their target genes:).

From the first beginning that how we specify cell types is different. So I totally got lost when we need to specify the overlapping ligands between two sender cells (I set two sender cells and one receiver cells) by the following codes.

ligand_expression_tbl = tibble(
  ligand = best_upstream_ligands, 
  CAF = expression[CAF_ids,best_upstream_ligands] %>% apply(2,function(x){10*(2**x - 1)}) %>% apply(2,function(x){log2(mean(x) + 1)}),
  endothelial = expression[endothelial_ids,best_upstream_ligands] %>% apply(2,function(x){10*(2**x - 1)}) %>% apply(2,function(x){log2(mean(x) + 1)}))

Could you kindly explain more how to do it by 10X sequencing data such as Seurat? Thanks so much!

**Comment by browaeysrobin** [comment]
Hi @rsggsr 

I redirect you to this open issue: #5.
The take home message is that you should make an expression table for your ligands with the average expression of each ligand in each cell type. This can be done in several ways and I give one suggestion in that issue.
