### ISSUE TITLE
Error on get_prioritization_tables()

### ISSUE THREAD

**Issue by qxiong2** [saeyslab/nichenetr#241]
Hi Team, 

I always got the following error when running get_prioritization_tables(), I am using Seurat v5 and nichenetr 2.0.4

> prioritization_tables = get_prioritization_tables(output, prioritizing_weights)
Error in `auto_copy()`:
! `x` and `y` must share the same src.
`x` is a <tbl_df/tbl/data.frame> object.
`y` is `NULL`.
Set `copy = TRUE` if `y` can be copied to the same source as `x` (may be slow).
Run `rlang::last_trace()` to see where the error occurred.

Please help me with this, thank you.

**Comment by qxiong2** [comment]
I solved it, this is because I don't have spatial data.

**Comment by arunchakra** [comment]
how do you solve this issue? what did you do?
