### ISSUE TITLE
Modeling Inquiry

### ISSUE THREAD

**Issue by xuansuyang** [saeyslab/nichenetr#244]
Firstly, thank you for developing this tool. I have a question regarding the modeling section. In the optimized_source_weights_df, there are two columns, namely avg_weight and median_weight. Could you please clarify what each of these columns represents? Additionally, when proceeding with the modeling steps, which column's weight values are utilized?

**Comment by csangara** [comment]
Hi,

The column represents the way the weights are aggregated between different rounds of parameter optimization. We used a five-fold cross-validation procedure to optimize the weights for the data sources and hyperparameters, as described in the [MultiNicheNet paper](https://www.biorxiv.org/content/10.1101/2023.06.13.544751v1.full) (**Parameter optimization via NSGA-II** in Methods and **Supplementary Note 2**). These `avg_weight` and `median_weight` columns are respectively the average and median of the weights across all folds. Specifically, it was computed using the 25 parameter settings in each fold with the highest  geometric average over the four objective functions. The final model uses the median weight, but as you can see in Supplementary Notes Figure 2.3 and 2.4, there is not much difference in performance between using the average and median.

**Comment by xuansuyang** [comment]
Thank you for your response. I'll take a look at the paper later. Wishing you a happy life.
