### ISSUE TITLE
Inquiry about Signaling and Gene Regulatory Networks Data in Omnipath and NicheNet

### ISSUE THREAD

**Issue by xuansuyang** [saeyslab/nichenetr#249]
Firstly, thank you very much for developing this tool. I would like to inquire about the sources in the signaling-network and gr-network, specifically omnipath_ABC, omnipath_D, omnipath_directional, omnipath_undirectional, NicheNet_LT_frequent, and NicheNet_LT_infrequent. I searched in Omnipath and NicheNet but did not find them. Therefore, I would like to ask where these data come from in Omnipath and NicheNet.

**Comment by csangara** [comment]
You will be able to find the explanation of the model construction of NicheNet v2 in the MultiNicheNet preprint. The part on NicheNet_LT_(in)frequent is described in Supplementary Note 1. Moreover, the scripts on model construction is also deposited at https://zenodo.org/records/8016880, under NicheNet_V2.zip. For example, you can find how omnipath_ABC was generated under networks/scripts/gene_regulatory/Omnipath/process_omnipath_gr.R.
