### ISSUE TITLE
Zenodo Data Inquiry

### ISSUE THREAD

**Issue by xuansuyang** [saeyslab/nichenetr#255]
Hello, first of all, thank you for developing the NicheNet tool. I noticed the file ligand_target_matrix_nsga2r_final_mouse.rds while modeling with the data uploaded to Zenodo. I would like to ask if this file is constructed based on other files in Zenodo. If not, what are the differences between the ligand_target_matrix I construct using files like lr_network_mouse_21122021.rds and gr_network_mouse_21122021.rds from Zenodo and the one you have built?

**Comment by csangara** [comment]
It should be the same if you use the optimized parameters we provided.
If you'd like to know more, you can check out https://zenodo.org/records/8016880, NicheNet_V2.zip, model_construction/scripts/.
