### ISSUE TITLE
extracting expression data from seurat 

### ISSUE THREAD

**Issue by skim245** [saeyslab/nichenetr#26]
Thank you for developing this great tool !

I would also like to use Circos plot for my seurat object 

and need help on creating my own "expression data of interacting cells"

are there any simple ways to extract this information from Seurat object? 

Thank you : )

**Comment by browaeysrobin** [comment]
Hi @skim245 ,

You can easily extract the average expression of each cell type in your data via the `Seurat::AverageExpression()` function (your cell types should be the identity class). More manual work would be to extract the gene expression matrices (in the data slots of your RNA assay) and apply some manipulations on that matrix.
