### ISSUE TITLE
I cannot run the "get_weighted_ligand_receptor_links" and "prepare_ligand_receptor_visualization" while I have nichnetr installed

### ISSUE THREAD

**Issue by pariaaliour** [saeyslab/nichenetr#262]
Dear Saeyslab team,
Thanks for this very helpful package. 
I am not sure why I cannot run "get_weighted_ligand_receptor_links" and "prepare_ligand_receptor_visualization" functions. I am following the tutorial exactly but not sure what is the problem. 
I have loaded the below libraries: 
library(Seurat)
library(SeuratObject)
library(tidyverse)
library(nichenetr)
ligand_receptor_links_df <- get_weighted_ligand_receptor_links(
best_upstream_ligands, expressed_receptors,
lr_network, weighted_networks$lr_sig) 
Error in get_weighted_ligand_receptor_links(best_upstream_ligands, expressed_receptors,  : 
  could not find function "get_weighted_ligand_receptor_links"
I appreciate your comment on this.
Thanks,
Paria

**Comment by csangara** [comment]
Hi, these are new functions from nichenetr version 2.1.0, can you check if you have the latest version?

**Comment by pariaaliour** [comment]
Thanks for the reply. You're right, there was problem with the version. I updated it and it worked.
Thanks,
Paria
