### ISSUE TITLE
missing function for circos plot visualization

### ISSUE THREAD

**Issue by cklee7** [saeyslab/nichenetr#269]
Hi,

Thank you for this nice package! I would like to visualize my NicheNet output in a circos plot following this vignette 
https://github.com/saeyslab/nichenetr?tab=readme-ov-file#:~:text=Seurat%20Wrapper%20%2B%20circos%20visualization

but I ran into this error when I tried to run the assign_lignads_to_cell_type() function.

> ligand_type_indication_df<-assign_ligands_to_cell_type(seuratobj,
                                                         nichenet_output$top_ligands,
                                                         celltype_col="cell_type")
Error in assign_ligands_to_cell_type(seuratobj, nichenet_output$top_ligands,  : 
  could not find function "assign_ligands_to_cell_type

The current version of nichenetr I have is 2.1.0. I'm not sure how to proceed as I'm new to bioinformatics and still learning how to troubleshoot, I really appreciate your time and help in this matter!

**Comment by csangara** [comment]
Hi @cklee7,

It seems like there might be a typo - the function is named `assign_ligands_to_celltype` (there is no underscore between "cell" and "type"), can you try it again?

**Comment by cklee7** [comment]
Hi, I restarted my session and found the function. Thanks so much!
