### ISSUE TITLE
get_expressed_genes() with Integration Workflow

### ISSUE THREAD

**Issue by uberholzer** [saeyslab/nichenetr#29]
I'm getting the following error when using `get_expressed_genes()` on a receiver Seurat object that was created using the integration assay: 

> Seurat object is result from the Seurat integration workflow. Make sure that this way of defining expressed genes is appropriate for your integrated data. The expressed genes are defined based on the integrated slot.

 This error comes after I set the default assay to "RNA", which the Seurat team has indicated should be used for analyzing gene expression data (FAQ 4 here: https://satijalab.org/seurat/faq). Should I instead be using the "integrated" assay as the default for NicheNet?

Thanks!

**Comment by browaeysrobin** [comment]
Hi @uberholzer 

I think this is not an error, but just a warning. Can you check this?
But to use the RNA slot, you can change the parameter `assay_oi` of the `get_expressed_genes()` function to `assay_oi = RNA` (it might be that you need to reinstall nichenetr to enable this though). This will use the RNA slot to define expressed genes instead of the integrated slot. The set default assay of the Seurat object does not matter here.

**Comment by uberholzer** [comment]
@browaeysrobin I am still getting the error even after re-installing nichnetr. 

Here is the block of code I am running:

```
CTOI <- "pDC"
receiver = c("pDC")
Idents(object=seuratObj) <- "celltype_fine"
DefaultAssay(seuratObj) <- "RNA"
expressed_genes_receiver = get_expressed_genes(receiver, seuratObj, pct = 0.10,assay_oi = "RNA")
background_expressed_genes = expressed_genes_receiver %>% .[. %in% rownames(ligand_target_matrix)]
sender_celltypes = c("AM", "Mixed T", "Club cell", "Proliferating T", "Ciliated cell",
                     "Neutrophil", "mDC", "NK", "Proliferating Plasma Cell", "Plasma cell", "Mature B", "pDC", "Mast cell")
list_expressed_genes_sender = sender_celltypes %>% unique() %>% lapply(get_expressed_genes, seuratObj, 0.10)
expressed_genes_sender = list_expressed_genes_sender %>% unlist() %>% unique()
```

Should I assume the function is working properly on the RNA assay?

**Comment by browaeysrobin** [comment]
Hi @uberholzer 

Do you get output for `expressed_genes_receiver` ? If yes then `get_expressed_genes()` just gives a warning and not an error. 
I think it will just be a warning and everything is working properly on the RNA assay.

**Comment by uberholzer** [comment]
Yes, we are getting an output and the data is interpretable. Thanks!
