### ISSUE TITLE
Can NicheNet be used for analyzing three groups?

### ISSUE THREAD

**Issue by Ldec12** [saeyslab/nichenetr#291]
Can NicheNet be used for analyzing three groups? Do we need to break it down into pairwise comparisons?

Thanks

**Comment by csangara** [comment]
Indeed, you'll either have to break it into pairwise comparisons or perform a one vs two DE analysis to define the gene set of interest. If you have multiple samples for each condition, also check out our [MultiNicheNet extension](https://github.com/saeyslab/multinichenetr) to see if it is more suitable for your use case.
