### ISSUE TITLE
Receiver cells in differential analysis

### ISSUE THREAD

**Issue by Cacti-Jiang** [saeyslab/nichenetr#294]
Hi,
I am wondering how to select receiver cells in the differential cell-cell interaction analysis. Specifically, when considering the differentially interactions between two conditions (Condition A vs Condition B) that induce cell type transition (from progenitor to differentiated cells), where the differentiation genes act as target genes. Should we use (progenitor+differentiated cell) or (progenitor in Condition A+differentiated cell in Condition B) or (progenitor in Condition A + progenitor in Condition B) as receiver cells?

**Comment by csangara** [comment]
Hi,

Sorry for the late reply. Closing this as Robin has provided you the answer in the MultiNicheNet repo.
