### ISSUE TITLE
Only activating interactions or also repressing?  

### ISSUE THREAD

**Issue by innaaver** [saeyslab/nichenetr#296]
In the Nichenet model, if a target gene is repressed by a ligand-receptor interactions is it considered a target? Or does the model only take into account cases where ligand-receptor has a positive/activating/up-regulating impact on the target?

**Comment by csangara** [comment]
Yes, we consider both up and downregulation between ligands and targets.
For more information, please check out [this FAQ answer](https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#can-nichenet-also-calculate-ligand-receptor-interactions-that-specifically-downregulates-target-genes-or-can-nichenet-distinguish-between-target-genes-that-are-upregulated-or-downregulated-due-to-a-ligand-receptor-interaction).
