### ISSUE TITLE
Couldn't install nichenetr

### ISSUE THREAD

**Issue by yujike1122** [saeyslab/nichenetr#307]
Couldn't install nichenetr, I am using R version 4.4.1, see the error below:

> if(!requireNamespace("devtools", quietly = TRUE)) {
+   install.packages("devtools") 
+ }
> 
> devtools::install_github("saeyslab/nichenetr")
Downloading GitHub repo saeyslab/nichenetr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/saeyslab/nichenetr/tarball/HEAD' failed

> devtools::install_github("saeyslab/nichenetr", ref = "v2.0.0")
Downloading GitHub repo saeyslab/nichenetr@v2.0.0
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/saeyslab/nichenetr/tarball/v2.0.0' failed

> devtools::install_github("saeyslab/nichenetr", ref = "v2.0.4")
Downloading GitHub repo saeyslab/nichenetr@v2.0.4
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/saeyslab/nichenetr/tarball/v2.0.4' failed

**Comment by Eisuan** [comment]
Dear user,
Based on your error report, the issue seems to be related to the internet connection.

Try to download the package when you are sure you have a stable internet connection.
Changing the timeout may also help  (_e.g._ options(timeout=600) ). 

Best regards,
Daniele
