### ISSUE TITLE
metadata column being read as dataframe even after updating seurat object in step by step tutorial

### ISSUE THREAD

**Issue by Shubhra1994** [saeyslab/nichenetr#309]
Hi, Thanks for this method.
I am using the tutorial here [step by step tutorial](https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md) 

My seurat object has cell type in "celltype" column and when I run 
```

int_obj <- SetIdent(int_obj, value = int_obj@meta.data$celltype)
receiver = "CD8+ T cells"
expressed_genes_receiver <- get_expressed_genes(receiver, seuratObj, pct = 0.05) 
expressed_genes_receiver <- get_expressed_genes("CD8+ T cells", seuratObj, pct = 0.05)  #this didnt work either
```

I get an error that the seurat object does not have "CD8+ T cells in its identity.
However if I run the same in one single wrapped as follows, I have no issues:
```
int_obj <- SetIdent(int_obj, value = int_obj@meta.data$celltype)
Idents(int_obj)

#perform agnostic nichenet
nichenet_output_agnostic <- nichenet_seuratobj_aggregate(
  seurat_obj = int_obj, 
  sender = "undefined",
  receiver = "CD8+ T cells", 
  condition_colname = "mutation_status",
  condition_oi = "mut",
  condition_reference = "wt",

  expression_pct = 0.05,
  ligand_target_matrix = ligand_target_matrix,
  lr_network = lr_network,
  weighted_networks = weighted_networks
  )
```

I tried event to specifically setting ident to CD8+ T cell with the same issue.
I think the function expects a list and gets a df?

Thanks!!

**Comment by Eisuan** [comment]
Dear user,
Thank you for using NicheNet.

I've just tried to reproduce your error, but I was unsuccessful.

Here's the code:
(R 4.4.0 and Seurat V5.0.0.)
```
# Seurat obj from scRNA-seq on PBMCs
head(Idents(filtered_concordant_cells_obj))
class(filtered_concordant_cells_obj)
```
<img src="https://github.com/user-attachments/assets/02edac12-a224-48aa-bced-5d0321dbaa3c" width="550" height="150">


```
receiver = "CD8 T"
expressed_genes_receiver <- get_expressed_genes(receiver, 
                                                filtered_concordant_cells, 
                                                pct = 0.05)
head(expressed_genes_receiver)
```
<img src="https://github.com/user-attachments/assets/d09b6992-1939-4d6b-80bc-d85c28832cd1" width="600" height="25">

```
# let's try to set idents in the way you did
filtered_concordant_cells_r <- SetIdent(filtered_concordant_cells, 
                                      value = filtered_concordant_cells@meta.data$azimuth_ref )

expressed_genes_receiver <- get_expressed_genes(receiver, 
                                                filtered_concordant_cells_r, 
                                                pct = 0.05)
head(expressed_genes_receiver)
```
<img src="https://github.com/user-attachments/assets/a8ebd836-d82b-4b2c-8687-d934ed2b0329"  width="600" height="25">



I can confirm that the NicheNet function is functioning correctly.  The function works even if your input is a list of receiver cell names. 

Therefore, it might be a problem related to your object. Can you confirm that Idents(int_obj) shows the expected output?

I suggest you try to adjust the source code from [here](https://github.com/saeyslab/nichenetr/blob/f9906f3a51ddc09405a04ece9de375688e03facb/R/application_prediction.R) **get_expressed_genes.Seurat** (line 1345) and make it run on your object. That could help you understand precisely what is not working and what to check. 

Best regards,
Daniele

**Comment by Shubhra1994** [comment]
Thanks Daniele! It had to do something with my seurat object! works now,
