### ISSUE TITLE
cannot download data from zenodo

### ISSUE THREAD

**Issue by dsb66** [saeyslab/nichenetr#31]
I am trying to follow the main vignette "NicheNet’s ligand activity analysis on a gene set of interest", but the first instruction fails with the following error:

ligand_target_matrix = readRDS(url("https://zenodo.org/record/3260758/files/ligand_target_matrix.rds"))
Error in readRDS(url("https://zenodo.org/record/3260758/files/ligand_target_matrix.rds")) : 
  cannot open the connection to 'https://zenodo.org/record/3260758/files/ligand_target_matrix.rds'
In addition: Warning message:
In readRDS(url("https://zenodo.org/record/3260758/files/ligand_target_matrix.rds")) :
  cannot open URL 'https://zenodo.org/record/3260758/files/ligand_target_matrix.rds': HTTP status was '500 Internal Server Error')

**Comment by dsb66** [comment]
The zenodo server problem has gone away. I can download the data now.

**Comment by 15013040212** [comment]
> The zenodo server problem has gone away. I can download the data now.
hi, I encountered the same problem, could you please share your solution? Thank you.
