### ISSUE TITLE
aligning ligands-receptor-targets

### ISSUE THREAD

**Issue by skim245** [saeyslab/nichenetr#33]
Thank you for the great work !! 

I would like to align top ligands and predicted receptors and targets together and would like to know if there is any easy way of doing this ! 

As mentioned in ligand-receptor-target circos plot, I've managed to generate two separate circos plots for ligand-target and ligand-receptor but wasn't sure how to overlay the two plots in a right alignment - as there is some overlay in targets in my ligand-target circos plots and thus results in mis-alignment to wrong category of receptors on top!

Thanks!

**Comment by browaeysrobin** [comment]
Hi @skim245 

For the moment there is no easy way to do this. I refer you further to this similar issue:  #https://github.com/saeyslab/nichenetr/issues/20
