### ISSUE TITLE
How to deal with inter-tumor heterogeneity

### ISSUE THREAD

**Issue by YangShi-PKU** [saeyslab/nichenetr#37]
Hi, first thanks for developing such a  awesome tool! I want to use Nichnetr to analyze my scRNA data from liver cancer, and I'm following the HNSCC guide.
In their initial paper, there is significant inter-patient heterogeneity (or to say, batch effect) in the malignant cells, but in this tutorial it does not take this into consideration. It only requires a gene is "expressed", but ignores which patient it comes from. So after the estimation of ligand activity (without considering the patient origin of cells), it's likely that a CAF ligand with "high activity" is expressed in patient 01, 03, but the p-EMT genes are mostly expressed in patient 02, 04. And such result could be misleading because interaction cannot cross different patients.
I wonder if there is some step I wrongly understand, if not, do you have some advice on dealing with such situation (inter-tumor or inter patient heterogeneity)? Any suggestion will be appreciated.

Thanks!
Yang

**Comment by browaeysrobin** [comment]
Hi @YangShi-PKU ,

You are right about this (but note that this is just an example to show how to perform a NicheNet analysis). To deal with inter patient heterogeneity, I would suggest doing a NicheNet analysis per tumor/patient. If you then want to draw general conclusions, you could look for correspondences between the results for the different tumors/patients.

**Comment by YangShi-PKU** [comment]
Thank you very much!
