### ISSUE TITLE
use with R for Mac

### ISSUE THREAD

**Issue by jamesreinecke** [saeyslab/nichenetr#42]
Hello, thank you for making this awesome resource.  Some people in my lab have started using it and it has yielded some interesting results.  I am hoping to start using it too, however, I am a mac user.  When i tried to install the Nichenetr package with the code provided i get the following message:
* installing *source* package ‘nichenetr’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 47974 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --slave 2>&1 < '/var/folders/hv/19_cb9rx1rjgdvdzn4_lgddr0000gn/T//Rtmp1GRZaJ/filebb5f2e6f4fec'
ERROR: lazy loading failed for package ‘nichenetr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/nichenetr’
Error: Failed to install 'nichenetr' from GitHub:
  (converted from warning) installation of package ‘/var/folders/hv/19_cb9rx1rjgdvdzn4_lgddr0000gn/T//RtmpbMArs0/fileba62197e2745/nichenetr_1.0.0.tar.gz’ had non-zero exit status

is this because nichenetr does not work with mac or might there be something else going on?

Thanks so much

**Comment by browaeysrobin** [comment]
Hi @jamesreinecke 

I don't think it's a general Mac problem. I am no Mac user myself but asked a colleague to install nichenetr and she had no problems (OS Catalina V10.15.5 and R version 4.0.0 RC -- "Arbor Day"). 
So there is probably another issue, but I fear I don't know what...
