### ISSUE TITLE
Receptors of ligand-to-target signaling paths

### ISSUE THREAD

**Issue by Wangteng65** [saeyslab/nichenetr#44]
Dear authors,
Thanks for this wonderful package!
I'm confused about the receptors of ligand-to-target signaling paths. There are some receptors existed in the inferred ligand-to-target signaling paths, and the ligand is sometimes directed targeted the target genes without receptor. Is it due to biological regulation or technical limitation that couldn't predicted the receptors between the liagand and its target genes?
Thank you so much！

**Comment by browaeysrobin** [comment]
Hi @Wangteng65 

Note that the network gives you only the known links documented in the databases and that these links are not always direct physical interaction links. For example: direct ligand-target links are coming from pathway databases and text mining databases that directly describe 'ligand X regulate expression of target A". Of course, this does not mean that this regulation occurs without ligand-receptor binding followed by signal transduction etc.
