### ISSUE TITLE
Error in installing nichenetr on Mac

### ISSUE THREAD

**Issue by ph329** [saeyslab/nichenetr#46]
Hi, 
Thanks for this very interesting tool, I've been playing around with it (version 0.1.0) for several months now with no issues. However I just tried to upgrade my version of Nichenet to access some new functions and I got the same error message as in #42 . I'm running MacOS Catalina v10.15.3. I tried restarting RStudio/starting a new R session and had the same error. 

checking for file ‘/private/var/folders/r5/sjlv78ys79nc00gtf7q_dl4s0q66gc/T/RtmpCjNuta/remotes15849674e2f7e/saeyslab-nichenetr-8b2fffc/DESCRIPTION’ ...
─  preparing ‘nichenetr’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘nichenetr_1.0.0.tar.gz’ (720ms)
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘nichenetr’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 88229 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --slave 2>&1 < '/var/folders/r5/sjlv78ys79nc00gtf7q_dl4s0q66gc/T//Rtmpt09Rt1/file1589d6515623'
ERROR: lazy loading failed for package ‘nichenetr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/nichenetr’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/nichenetr’
Error: Failed to install 'nichenetr' from GitHub:
  (converted from warning) installation of package ‘/var/folders/r5/sjlv78ys79nc00gtf7q_dl4s0q66gc/T//RtmpCjNuta/file158493e102e2e/nichenetr_1.0.0.tar.gz’ had non-zero exit status

**Comment by browaeysrobin** [comment]
Hi @ph329 

Recently, another Mac user (in addition to the one you already mentioned) reported problems installing nichenetr as well (check issue #45)

Unfortunately I have no clear idea what caused the problem  (probably an error in the combination Mac-Rstudio-Bioconductor-nichenetr; it seems that issues with Rstudio, Rstudio Cloud/Server, Docker, Conda, ... could be occuring), but in the end, that user was able to install nichenetr by installing the dependencies of nichenetr one by one (you can find them in the DESCRIPTION page), and then installing nichenetr.

Here under I will paste some other possible solutions that I suggested

---------------------------------------------------------------------------

1) If you were installing nichenetr from RStudio, I would first try to install nichenetr from a clean R session on the command line (so: open terminal --> launch R 4.0.2 --> devtools::install_github("saeyslab/nichenetr").
2) If that fails, and you have a form of Conda (e.g. Miniconda) installed on your computer, maybe remove it and then try to install nichenetr again
3) if that still fails: try reinstalling R and RStudio (downloading R from CRAN, and RStudio from rstudio.com), then install nichenetr (try Rstudio and R via terminal).
4) if that still fails: check the DESCRIPTION page of nichenetr and install each of the dependencies separately and then try to install nichenetr again.

If all these steps still failed:
you can check following sites for more information and see whether they might be useful for you:

https://github.com/jacobxk/setup_macOS_for_R
https://stackoverflow.com/questions/19533220/cannot-install-r-package-from-source-in-mac-osx-maverick
https://community.rstudio.com/t/killed-error-during-installation-for-many-packages/24239/8
https://stackoverflow.com/questions/58473798/macos-rstudio-accessing-wrong-clang-after-upgrade-to-catalina
