### ISSUE TITLE
How to adjust font size in render_graph?

### ISSUE THREAD

**Issue by linanzhang** [saeyslab/nichenetr#47]
I used the same commands as in the [tutorial](https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_target_signaling_path.md), however, I'm not able to generate a readable tree as shown in the tutorial. How to fix this issue? Thanks.

![Rplot](https://user-images.githubusercontent.com/37935731/89950863-70db1600-dbf8-11ea-85ee-6175e47aa1c2.png)

**Comment by browaeysrobin** [comment]
Hi @linanzhang 

You could play around with the arguments of the `DiagrammeR::render_graph` function (changing the layout might make it more readable), but I think exporting to Cytoscape or another network visualization tool will give you more options to customize how your graph looks like. 
I can also redirect you to this vignette from another lab, where they nicely visualize these NicheNet ligand-target paths 
https://github.com/saezlab/NicheNet_Omnipath/blob/master/07_LigandTargetPaths.md

**Comment by linanzhang** [comment]
Is there a working example to show how to import annotation_table.txt to Cytoscape? Thank you.

**Comment by browaeysrobin** [comment]
Normally via import --> import table (or something very similar). If you do that after importing the network, it will link the information in that table to the nodes of the network. For more information about working with Cytoscape, you can check their extensive tutorials and documentation.
