### ISSUE TITLE
Evaluation of ligand activies

### ISSUE THREAD

**Issue by srossk** [saeyslab/nichenetr#50]
Hi,
I would like to know if there is a guideline for setting a cutoff for ligands that were defined by the "predict_ligand_activities" function? For example, if I get activities with Pearson correlation coefficients around 0.01 or even negative ones, should those ligands get excluded from the following analysis?

Thanks in advance

**Comment by browaeysrobin** [comment]
Hi @srossk 

See this section in the FAQ to gain more insight in how to interpret these ligand activity pearson correlation values:

https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#how-should-i-interpret-the-pearson-correlation-values-of-the-ligand-activity-what-does-it-mean-when-i-have-negative-values

Don't hesitate to ask further questions if necessary.
