### ISSUE TITLE
Rhesus Macaque Data

### ISSUE THREAD

**Issue by shelby2919** [saeyslab/nichenetr#51]
I have single cell data from rhesus macaque that I want to analyze using nichenet. Currently, I am using organism="human". Of the roughly 19,000 genes I have in my Seurat object, roughly 13,000 of then intersect with the row names of the ligand_target_matrix, so I am wanting to know if this is OK, or if I will need to modify the row names of the ligand_target_matrix.

**Comment by browaeysrobin** [comment]
Hi @shelby2919 

This could be OK if macaque has the same gene symbols as human, but I have never worked on macaque data, so I am not aware of whether this is true. Therefore I would suggest that you look for a way to find a good one-to-one orthology conversion between human and macaque (check for example biomart, ncbi homologene), and then apply this on the ligand-target matrix and ligand-receptor network to change these symbols (using the step-by-step vignette https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md).
Maybe you will then be able to keep a larger set of genes from your Seurat object than just assuming that human and macaque gene symbols are the same.
