### ISSUE TITLE
mac issue

### ISSUE THREAD

**Issue by jamesreinecke** [saeyslab/nichenetr#56]
hello, i'm sorry for bringing this up again, i tried to manually download the zip instead of loading it through devtools and i get the following message:
Error in install.packages : file ‘~/Downloads/nichenetr-master (1).zip’ is not a macOS binary package

i think i recall someone was able to use Nichenetr with a mac but i'm wondering how they got around this

thanks so much, looking forward to hopefully using this program soon

**Comment by browaeysrobin** [comment]
Hi @jamesreinecke 

Did you already check this issue: https://github.com/saeyslab/nichenetr/issues/46 ? (and if the suggestions there don't work, this one https://github.com/saeyslab/nichenetr/issues/45)
