### ISSUE TITLE
how to interpret scores?

### ISSUE THREAD

**Issue by justinesjw** [saeyslab/nichenetr#57]
Hi! 

Thanks for creating NicheNet!

I may have missed this, may I know how these scores are generated?
![image](https://user-images.githubusercontent.com/26448066/96440275-5184e880-123a-11eb-96cb-8581f24bb270.png)

Thank you for your reply!

Best, 
Justine

**Comment by browaeysrobin** [comment]
Dear @justinesjw 

You can find some information about this in the following vignette:
https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md

For more detailed explanation about these scores, I refer you to the Online Methods and Supplementary Notes/Figures sections of the NicheNet paper.
