### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by quwz** [saeyslab/nichenetr#6]
Hello,

Thanks for the awesome package！
I am trying to use this:
![图片](https://user-images.githubusercontent.com/59106997/71305853-78a13c80-2414-11ea-94b1-0e099f15533f.png)

But then I get this error: Does not appear to be an R package (no DESCRIPTION).

![图片](https://user-images.githubusercontent.com/59106997/71305812-edc04200-2413-11ea-9740-7e82e9e5b0b0.png)
I don't know why it can't be installed.
I currently have version 3.6.1 of R.
Thanks!

**Comment by browaeysrobin** [comment]
Hello @quwz 

Can you try doing what they suggest here: https://github.com/r-lib/devtools/issues/1939. It seems to me that your problem might be similar. Let me know if the problem is solved then. If not, could you provide me with your session info?

**Comment by quwz** [comment]
Hi @browaeysrobin 
 
Many thanks for your reply. I tried ` Sys.setenv("TAR" = "internal") ` but still failed. 
And R gave the error that "
Downloading GitHub repo saeyslab/nichenetr@master
Error: Failed to install 'nichenetr' from GitHub:
incomplete block on file "
(eg.fig1)
![fig1](https://user-images.githubusercontent.com/59106997/71805041-1dbc4600-30a0-11ea-82a1-295de51374a0.png)

-----sessionInfo-------

![fig2](https://user-images.githubusercontent.com/59106997/71805061-2ad93500-30a0-11ea-9062-ff17063d524c.png)
![fig3](https://user-images.githubusercontent.com/59106997/71805072-3298d980-30a0-11ea-8bde-caf3e69d04b4.png)

Thanks for your time

**Comment by browaeysrobin** [comment]
Hi @quwz 

Can you try installing a few other packages from github with `devtools::install_github()` to check whether it is a nichenetr-specific problem on your pc or a general problem on your pc?

If it seems to be a general problem, you could maybe have a look at this https://lcolladotor.github.io/2019/09/18/windows-user-space-issues-with-installing-r-packages/

**Comment by browaeysrobin** [comment]
Hi @quwz 
Any more news on this?

**Comment by MWT122122** [comment]
Hi@Robin Browaeys

I have tried using **devtools::install_github()** to install other packages without  
So just installing this package will not work, the error  is as follows:
Error: Failed to install 'nichenetr' from GitHub:
  package ‘tibble’ not installed because it is not built for UCRT
