### ISSUE TITLE
NicheNet on CIBERSORT sorted cell-populations

### ISSUE THREAD

**Issue by cantaloupe5** [saeyslab/nichenetr#62]
Hello,

Thank you for creating such an amazing tool. [CIBERSORTx](https://www.nature.com/articles/s41587-019-0114-2) can produce cell-type specific gene expression profiles from bulk RNA-Seq. The authors have demonstrated that their algorithm's results correlate well with FACS-sorted cell-type transcriptomes. As you have used NicheNet on FACS-sorted bulk-RNA Seq data in this [paper](https://www.cell.com/immunity/pdf/S1074-7613(19)30368-1.pdf), I was wondering what your thoughts are on using NicheNet on these "_in silico_" sorted cell transcriptomes. Of course, I imagine NicheNet's results will not be as reliable (as you previously said: garbage in, garbage out) but are there any reasons to avoid this technique altogether?

Thank you.

**Comment by browaeysrobin** [comment]
Hi @cantaloupe5 
If that would be the only type of data you have to address your biological question, I think you could apply NicheNet to generate some hypotheses, but I would indeed be cautious in interpreting the results.
