### ISSUE TITLE
Heatmap for logfoldchange for receptors/ target genes on receiver cell 

### ISSUE THREAD

**Issue by jd10020** [saeyslab/nichenetr#65]
Dear nichenetr team,

First of all thank you for the package and the tutorial. Both are really helpful for my project. Right now I am comparing 2 timepoints from Seurat data. I followed the tutorial and everything worked fine. However, I saw at one point you explained how to make a heat map to check logFoldChnage for the ligands based on the Pearson value and using the FindMarkers function from the senders. I was trying to do the same but with the receptor and the receiver. I mean I calculated to logFC for my receiver, however I do not know how to combine it with my nichenetr data so I can plot a heat map. Do you know what can I do? or which code could help me with that?

Thanks in advance.

Diego

**Comment by browaeysrobin** [comment]
Hi @jd10020 

Do you mean you don't know how to combine your receptor-LogFC heatmap with the other plots in a combined heatmap? If that's the case, you could check the example of making a combined heatmap that I provided in the tutorials and adapt it (add a few layers); if you would struggle with that, I would suggest you would look into the documentation and tutorials of packages like cowplot and patchwork (recommended) on how to combine ggplots.
