### ISSUE TITLE
Allow unique seurat objects for sender and receiver with the nichenet_seuratobj_aggregate

### ISSUE THREAD

**Issue by dmitrikotov** [saeyslab/nichenetr#68]
Hello,

Thank you for the great tool. I find myself often using NicheNet to analyze receiver and sender populations from 2 separate seurat objects, however this doesn't seem to be currently supported in the nichenet_seuratobj_aggregate function. It would be great to be able pass arguments to individually specify seurat objects for the receiver and sender populations when running the nichenet_seuratobj_aggregate function, with the differential gene analysis for defining target genes being run on the receiver seurat object.

Thank you!

Dmitri

**Comment by browaeysrobin** [comment]
Hi @dmitrikotov,

Are there specific reasons why you don't want to just merge the Seurat objects before the NicheNet analysis? Because at this moment, I don't see myself why merging would be problematic (and thus also not why I would need to implement this change).

**Comment by dmitrikotov** [comment]
Hi @browaeysrobin,

Good point about just merging the objects. I likely wouldn't use the merged object for downstream visualization but it would work great as an input for NicheNet analysis. Thank you!
