### ISSUE TITLE
Vignette on using Bulk RNA-seq data 

### ISSUE THREAD

**Issue by kanekalla** [saeyslab/nichenetr#70]
Hi there,

Thanks for the wonderful tool.
Do you have a vignette to perform NicheNet analysis for flow-sorted Bulk RNA-seq data?

**Comment by browaeysrobin** [comment]
Hi @kanekalla 

Unfortunately there is no vignette specifically for bulk RNA-seq and we have no plans (at least not short term) to make one.

In the FAQ page, I mention some tips to start from the basic vignette for bulk RNA-seq data:
https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#can-i-use-nichenet-on-bulk-rnaseq-data-as-well-or-only-on-single-cell-data

The main point is that you just focus on the different steps in the NicheNet analysis pipeline and replace single-cell based analysis ways by a bulk RNA-seq counterpart (eg defining the geneset of interest by DE analysis via a dedicated bulk RNA-seq DE tool like EdgeR, DESeq2, limma).

**Comment by kanekalla** [comment]
Thank you @browaeysrobin
