### ISSUE TITLE
Nichenetr

### ISSUE THREAD

**Issue by Alexxyz123** [saeyslab/nichenetr#74]
when I run nichenet_seuratobj_aggregate there happened this error：
Error: Problem with `filter()` input `..1`.
x object 'avg_logFC' not found
ℹ Input `..1` is `p_val_adj <= 0.05 & abs(avg_logFC) >= lfc_cutoff`.
Run `rlang::last_error()` to see where the error occurred.

please let me know why I met this problem, since it's ok when I run the same dataset several days before.
Furthermore, seurat version was 4.00 nichenetr version was 1.00

**Comment by browaeysrobin** [comment]
Hi @Alexxyz123 

Can you try re-installing nichenetr? After re-installing it should work in combination with both Seurat version 4 and lower (see issue #67)
