### ISSUE TITLE
Explanation for few terms

### ISSUE THREAD

**Issue by Sharks28** [saeyslab/nichenetr#78]
I am a biologist who have dabbled into the world of informatics.  I am a little confused about regulatory potential heatmap.  From what I understand, this parameter leverages knowledge base to predict the probability for a ligand to regulate particular gene in the gene set.  Am I right?  Also, I am not sure on how to read the units for weighted regulatory potential.  Most example heatmaps seems to have a pretty low regulatory score.  Would you let me know what is the upper-bound for the score and what is a good regulatory potential score?

Thank you

**Comment by browaeysrobin** [comment]
Hi @Sharks28 

You are right that the regulatory potential give a probability for a ligand to regulate a particular gene based on the integrated prior knowledge.

These scores are useful to eg check the top n predicted targets genes of a ligand.
The interpretation of the 'absolute values' scores is harder though. The scores are indeed very low, but it is very hard to say which values would be very high and confident (and thus a 'good' regulatory potential score) and which would be low and non-confident. 
But on the heatmap, you can be sure that the indicated scores are high enough, and that indicated interactions there are supported by a few types of evidence (which you could check for individual ligand-target links via the https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_target_signaling_path.md vignette).
