### ISSUE TITLE
Can I use NicheNet on data derived from open resource?

### ISSUE THREAD

**Issue by yujiyokouchi** [saeyslab/nichenetr#79]
Hello. Thank you for doing such an important job of combining so much human data into one accurate ligand-targeted model. It is really a great job.

I would like to explain the question I have.
I am planning to take an existing open-resource dataset and apply NicheNet to a specific cell lineage within it.

From what I can tell, the use of NicheNet in single-cell RNAseq data is often done with datasets generated by 10XGenomics' Chlomium system. This system reads 200-300 bases from the 3'-end of the mRNA and is capable of profiling the transcripts of about 3,000 genes per cell.

In contrast, the open-resource scRNAseq dataset that I am going to use comes from the mouse organogenesis single cell atlas (MOCA) at  University of Washington (https://oncoscape.v3.sttrcancer.org/atlas.gs.washington.edu.mouse.rna/landing , https://doi.org/10.1038/s41586-019-0969-x.) This MOCA data is generated by a proprietary method called combinatorial indexing-RNA-seq (sci-RNA-seq). This method is capable of reading longer regions of mRNA, but the number of genes that can be analyzed per cell is only about 500.
　Can NicheNet be applied to such a dataset, which is less complex than the Chlomium-derived data?　Will it be possible to identify meaningful information?　For example, is it possible to find candidate developmental regulatory signaling pathways that are essential for the differentiation of one progenitor cell into another?
　
I would be grateful for your answer.

**Comment by browaeysrobin** [comment]
Hi @yujiyokouchi,

In theory it could be possible, but no guarantee here. Maybe you will need to tweak the way you define DE genes between your cell populations of interest to have "enough" genes in the geneset of interest to predict ligand activities (minimal recommended number of genes in the geneset of interest: +- 20, but preferably a bit higher).

**Comment by yujiyokouchi** [comment]
Thank you very much for your response. You advised me that "I may need to tweak the way I define DE genes among the target cell populations to include enough genes in the target gene set to predict ligand activity". However, I am new to NicheNet and find it difficult to fully understand your advice.
What exactly should I do?　If you could refer me to an appropriate vignette or something similar, I would appreciate it.

Thank you for your time.

**Comment by browaeysrobin** [comment]
Hi @yujiyokouchi 

I am referring here to this part of the seurat vignette:

https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md#2-define-a-gene-set-of-interest-these-are-the-genes-in-the-receivertarget-cell-population-that-are-potentially-affected-by-ligands-expressed-by-interacting-cells-eggenes-differentially-expressed-upon-cell-cell-interaction

In that code we define the set of DE genes (which is demonstrated via the Seurat FindMarkers function, but could be done with other DE methods as well). If  you won't find (enough) DE genes, you could lower the used thresholds or use a different way of DE analysis. 
I am not familiar with this type of data in general, nor with your specific dataset, so I cannot suggest more specific actions to take.

**Comment by yujiyokouchi** [comment]
Hi Mr. Robin Browaeys

Thank you very much for introducing me to the vignette related to my 
question. Your explanation seems to help me find a solution to my 
problem. Now I will actually check it with my own data.

I wish you and NicheNet all the best in your future work.

Yuji Yokouchi
Kumamoto University, Japan.


----- Original Message -----
> Hi @yujiyokouchi 
> 
> I am referring here to this part of the seurat vignette:
> 
> https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md#2-define-a-gene-set-of-interest-these-are-the-genes-in-the-receivertarget-cell-population-that-are-potentially-affected-by-ligands-expressed-by-interacting-cells-eggenes-differentially-expressed-upon-cell-cell-interaction

> 
> In that code we define the set of DE genes (which is demonstrated via 
the Seurat FindMarkers function, but could be done with other DE methods 
as well). If  you won't find (enough) DE genes, you could lower the used 
thresholds or use a different way of DE analysis. 
> I am not familiar with this type of data in general, nor with your 
specific dataset, so I cannot suggest more specific actions to take.
