### ISSUE TITLE
Error message while installing NichenetR from devtools command

### ISSUE THREAD

**Issue by baplu** [saeyslab/nichenetr#80]
Hi,
thank you for wonderful package. I am extremely new to R programming so I am sorry I am asking you naive questions.
I am trying to follow the Nichenet vignette but I couldn't install packages in the first place.
I follow following code:
devtools::install_github("saeyslab/nichenetr")

I have Seurat V4 preinstalled. After running installation devtools command I am getting following message.

Skipping 1 packages not available: limma
Installing 24 packages: xfun, RcppArmadillo, haven, utf8, cli, knitr, cpp11, pillar, vctrs, dplyr, tibble, broom, tidyr, viridisLite, spatstat.utils, spatstat.data, spatstat.sparse, spatstat.geom, caTools, zoo, XML, spatstat.core, Seurat, limma
Installing packages into ‘\\nas-fa0efsusr1/raibu/My Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Fehler: Failed to install 'nichenetr' from GitHub:
  (konvertiert von Warnung) package ‘limma’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
 
I would be grateful, if you could give me some possible way of installing package

Thank you so much

Baplu Rai
 
--

**Comment by browaeysrobin** [comment]
Hi @baplu 

Could you try once running

`if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("limma")`

before installing nichenetr?

**Comment by baplu** [comment]
Hi @browaeysrobin 
thank you so much for fast response. Your suggestion saved my day. 
I installed limma then follow the Devtools command.
Now it is installed. :)
Keep building awesome package like this.
Best wishes from Germany.

**Comment by Kiliankleemann** [comment]
This saved me as well thank you!!!

**Comment by starrynight27** [comment]
Hi, I had the same issue.  I tried to install limma it goes through and then when I try to install Nichenet it comes up with this error: 

Error in install.packages : Updating loaded packages
Downloading GitHub repo saeyslab/nichenetr@HEAD
Skipping 2 packages not available: ComplexHeatmap, limma
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/1l/x586c0wd6y5_89xmy732lj140000gq/T/RtmpDiDo0L/remotesb48a26fff005/saeyslab-nichenetr-d8a5b5a/DESCRIPTION’ (335ms)
─  preparing ‘nichenetr’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts (382ms)
─  checking for empty or unneeded directories
─  building ‘nichenetr_2.1.5.tar.gz’
   
ERROR: dependency ‘ComplexHeatmap’ is not available for package ‘nichenetr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/nichenetr’
Warning in i.p(...) :
  installation of package ‘/var/folders/1l/x586c0wd6y5_89xmy732lj140000gq/T//RtmpDiDo0L/fileb48a2f03fafd/nichenetr_2.1.5.tar.gz’ had non-zero exit status


Many thanks!
