### ISSUE TITLE
Acquirement of ligand target matrix

### ISSUE THREAD

**Issue by Xiao-ZQ** [saeyslab/nichenetr#81]
Hello, I has been learning this awesome R packages for discovering new interaction between cells.
Here is a question about the usage of this package. I notice that it is needed to have a prior matrix of ligand-target interaction. 
So my question is : **how is this matrix acquired**? 
I know the data was from database like KEGG, but how are these data merged and converted into a prior matrix?
Any answer of my question is appreciated.

**Comment by browaeysrobin** [comment]
Dear @Xiao-ZQ ,

The details about this are all described in the Supplementary Notes and Online Methods section of the paper https://www.nature.com/articles/s41592-019-0667-5. If you don’t have access to the paper, I can always send you a pdf.

There is also an overview figure and some explanation this in the following vignette: https://github.com/saeyslab/nichenetr/blob/master/vignettes/model_construction.md, where you can also find the code on how to calculate the ligand-target matrix yourself starting from input ligand-receptor, signaling and gene regulatory data sources.

Best regards,
Robin
