### ISSUE TITLE
question: origin of the data

### ISSUE THREAD

**Issue by GildasLepennetier** [saeyslab/nichenetr#82]
Dear Contributors,
I am interested in the creation of the "geneinfo_human.rda" object.
I quickly search and did not find the origin not the version of the data. I suspect some biomaRt steps.
I think it would be great to have the methods described somewhere, and even why not a little function to update the R object if necessary.
Regards,

**Comment by browaeysrobin** [comment]
Hi @GildasLepennetier 

There was some information about that in Supplementary Note 13 of the paper, but to summarise: we started from the org.Hs.eg.db R package and used NCBI HomoloGene and biomaRt-Ensembl to define one-to-one orthologs between mouse and human.

We are now also working on an updated prior model behind NicheNet, and an updated 'geneinfo' object. Once we release that, we will also provide some code so users can update that geneinfo object if they want - thank you for this suggestion.
