### ISSUE TITLE
Error with latest spatstat version when installing NicheNet

### ISSUE THREAD

**Issue by a-munoz-rojas** [saeyslab/nichenetr#83]
When trying to install nichenetr, I got the following error:
```
Error: object ‘markvario’ is not exported by 'namespace:spatstat'
Execution halted
```

This was fixed by downgrading spatstat to 1.64-1:

`remotes::install_version(package = "spatstat", version = package_version("1.64-1"))
`
It's probably better to fix in a future update of nichenetr. It seems that the markvario function is now in spatstat.core, but I'm not certain.

**Comment by browaeysrobin** [comment]
Hi @a-munoz-rojas 

The spatstat function is not a direct dependency of nichenetr, 
It is a dependency of Seurat though, which is a dependency of nichenetr. I think by upgrading Seurat, this issue should not occur anymore.
