### ISSUE TITLE
Question: Can I perform Nichenet on combined Human/mouse data

### ISSUE THREAD

**Issue by khsaleh88** [saeyslab/nichenetr#84]
Hi! Thank you for this great package! 
I'm trying to combine human and mouse scRNA seq data currently, and I would like to eventually find ligand/receptor interactions between some human and mouse cells (we do human transplantation into mouse).  Do you think that this could be at all possible to do with Nichenetr?
My other thought was to look at FinaMarkers for the specific subclusters I would like to look at and perform Nichenetr on a gene set of interest.

Thank you!

**Comment by browaeysrobin** [comment]
Hi @khsaleh88 

This could be possible. I would recommend doing this by changing your mouse gene symbols of your data to their human one-to-one orthologs and then just do the analysis.
