### ISSUE TITLE
Error in DE analysis

### ISSUE THREAD

**Issue by smilesw** [saeyslab/nichenetr#86]
hello, thanks for developing nice tools. 
I ran into unpredicted errors when getting log fold change information of ligands from sender cells as follows.

DE_table_all = Idents(kidney) %>% levels() %>% intersect(sender_celltypes) %>% lapply(get_lfc_celltype, seurat_obj = kidney, condition_colname = "group", condition_oi = condition_oi, condition_reference = condition_reference, expression_pct = 0.10) %>% reduce(full_join)

--> Error in (function (classes, fdef, mtable)  : unable to find an inherited method for function ‘reduce’ for signature ‘"list"’

I don't know where it comes from. Is a certain package necessary? 
Would you give me a help to solve this error?  Thanks in advance.

**Comment by browaeysrobin** [comment]
Hi @smilesw 

Can you try `purrr::reduce` instead of `reduce`?

**Comment by smilesw** [comment]
Thank for your answer. 
Although I perform analysis of log fold change after "library (purrr)", it did not work. 
However, "purrr::reduce" instead of "reduce" works. 
I really appreciate your guide.
