### ISSUE TITLE
Problems about  installing  nichenetr

### ISSUE THREAD

**Issue by chenjunhui** [saeyslab/nichenetr#88]
Hi,

When  we install the  packages on Ubuntu 20.04.2 LTS， and we meet the fowlling errors.

Error: .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: Tcl/Tk support is not available on this system
Execution halted

Would  you like to  give us some suggestions?

best wishes

**Comment by browaeysrobin** [comment]
Hi @chenjunhui 

Your error message 'error: Tcl/Tk support is not available on this system' seems a general R/Ubuntu problem (and not a nichenetr-specific one). I have never encountered this issue myself, so I can't provide help based on my experience. I would suggest you look online for solutions to this error.
