### ISSUE TITLE
inquiry regarding nichenet computing and error running predict_ligand_activities 

### ISSUE THREAD

**Issue by or-lazarescu** [saeyslab/nichenetr#9]
when nichenet is applied to find regulatory networks between one cluster to the rest of the clusters in seurat object, does it compute cluster to clusters or group of cells to individual group of cells? more specifically - does it take into consideration that the receiver set of cells is composed of different cell types (clusters) or composed of different individual cells? 

also, regardless of that, what does the following error mean:

Error in evaluate_target_prediction(setting, ligand_target_matrix, ligands_position) : 
  all genes have same response

**Comment by browaeysrobin** [comment]
Hi @or-lazarescu 

I am not sure what you exactly mean with the first question, but if you give multiple clusters (representing one cell type) as input for the receiver cell type, it will take into account that the receiver cell type consists of multiple clusters. It will do so by calculating expressed genes for each of the clusters separately, and then pooling these expressed genes per cluster to get the entire set of expressed genes for the receiver cell type.

Error in evaluate_target_prediction(setting, ligand_target_matrix, ligands_position) : all genes have same response --> this means that in your 'setting' all genes are considered to be differentially expressed (DE) or all genes are considered to be background, whereas some genes should be DE, and the rest background.

**Comment by or-lazarescu** [comment]
by your answer i can tell you understood my question. thanks a lot!
