### ISSUE TITLE
Nichenet and microarray data

### ISSUE THREAD

**Issue by FFranZZ** [saeyslab/nichenetr#90]
Hi, I have a possibly very naive question: is it possible to use microarray data on Nichenet? Do you have any recommendations?  Thank you.

**Comment by browaeysrobin** [comment]
Dear @FFranZZ 

It depends. If you have microarray data of different sorted cell populations, and a data design that enables you to ask your research question, you can use NicheNet. 
You will just need to tweak the different steps of the workflow to microarray yourself (https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_activity_geneset.md).
