### ISSUE TITLE
6) Add log fold change information of ligands from sender cells (issue)

### ISSUE THREAD

**Issue by DRSEI** [saeyslab/nichenetr#91]
Hi 

I am trying to do DE analysis for each sender cell type but keep getting Error: Cannot find 'celltype' in this Seurat object. 
is anyone having a similar issue or could anyone advise me on how to fix this issue?

> library(nichenetr)
> # DE analysis for each sender cell type
> # this uses a new nichenetr function - reinstall nichenetr if necessary!
> DE_table_all = Idents(seuratObj) %>% 
+   levels() %>% 
+   intersect(sender_celltypes)%>% 
+   lapply(get_lfc_celltype, seurat_obj = seuratObj, condition_colname = "time.point",
+ condition_oi = condition_oi, condition_reference = condition_reference, expression_pct = 0.10) %>%
+   purrr::reduce(full_join)
Error: Cannot find 'celltype' in this Seurat object

**Comment by browaeysrobin** [comment]
Dear @DRSEI 

Can you have a look at what I suggest in this issue; #85 ?

**Comment by DRSEI** [comment]
Dear @browaeysrobin 

Thank you so much. problem solved
