### ISSUE TITLE
how to read regulatory potential heatmaps

### ISSUE THREAD

**Issue by shokohirosue** [saeyslab/nichenetr#92]
Hi team,

Thank you for developing such a great package.
May I ask you about the heatmap visualising regulatory potential between prioritized ligands vs predicted target genes?

From this heatmap, am I allow to compare regulatory potential across a specific target gene? For example, in this figure can I say App is the most effective ligand for Gbp4 expression in the receptor cells?

Thank you so much for your help.

![Screenshot 2021-07-16 at 11 01 45](https://user-images.githubusercontent.com/39588560/125930761-18ef07f0-6eee-43f4-b305-78cb3af794f8.png)

**Comment by browaeysrobin** [comment]
Hi @shokohirosue 

What you can conclude from comparing the regulatory potential scores, is (more or less) that there is more prior knowledge for ligand-target links with higher regulatory potential scores.
Whether the link with the most prior knowledge is really the most effective, is not certain though. Eg well-studied ligands will have 'more' prior knowledge evidence, but are not necessarily more strongly involved in a specific biological system.

So to conclude: I would not say that App is the most effective ligand in regulating Gbp4 - but there is much prior evidence that such this link can exist

**Comment by shokohirosue** [comment]
Hi, thank you very much for your quick reply!

Thank you for clarifying this. I sense that the heatmap is plotted based on the absolute value, not normalised by row or column etc. so you can only compare in one direction. Let me know if I am wrong.

Thank you very much!

**Comment by linzhangTuesday** [comment]
Hello, Thanks for the wonderful tool of Nichenet.

My confusion is that a higher regulatory potential does not indicate a more effective ligand, as in the case of App here. How would the person correlation of higher regulatory potential in geneset of interest, speak for more active ligand activity?

**Comment by browaeysrobin** [comment]
Hi @linzhangTuesday 

I think I understand your confusion (if not, let me know!)

The regulatory potential should better be interpreted within one ligand versus between ligands; meaning: if targetA has higher scores for ligandX compared to target B, you can confidently say there is more evidence supporting ligandX-targetA regulation vs ligandX-targetB regulation. Whether this is "more effective from molecular perspective" is something we cannot say. However, I would be way more cautious in comparing ligandX-targetA vs ligandY-target A scores. The reason for this has to do with how the regulatory potential scores are calculated with the Personalized PageRank approach, and with how we optimized the model (by maximizing target gene and ligand activity prediction - two prediction performances that do not compare between ligands).

For calculating the ligand activities, we will look per ligand whether the genes in the geneset of interest have in general higher regulatory potential scores for that ligand, compared to genes in the background. If that's the case, it means that genes with more evidence to be a target of a ligand are enriched in the geneset, indicating that this ligand might be active. This is done per ligand, so only the scores within one ligand are important here.
