### ISSUE TITLE
self-links detected

### ISSUE THREAD

**Issue by mlin11** [saeyslab/nichenetr#93]
Hi NicheNet Team,

Thank you for this great tool for investigating cell-cell interactions.

 I applied it on a single-cell RNA-seq data. Nichenetr worked well, and some interesting interactions showed up. When I checked the ligand-receptor interaction results, I found a self-link interaction: CD99-CD99. I read the Nature Methods paper and these self-links seem to have been removed from the signaling network though. Could you please give me some guidance on interpreting this self-link interaction?

The nichenetr package used is : nichenetr_1.0.0. 

Thanks,
Mao

**Comment by browaeysrobin** [comment]
Dear @mlin11 

The self-links are only removed in the intracellular part of the signaling network (to avoid problems with the personalized pagerank calculations etc).

If some gene can encode for both a ligand and receptor that can interact (like CD99), this ligand-receptor interaction should still be, and thus is, present in the ligand-receptor network. Hence why you can find these self-links in the final output.
