### ISSUE TITLE
how to add outer layer/track layer in the exsting circus plot 

### ISSUE THREAD

**Issue by adesalegn** [saeyslab/nichenetr#94]
Hi 
Thanks for the package and I have a question.
My question basically is how to add an additional track layer on the circus plot to indicate some information as indicated in the post (https://github.com/saeyslab/nichenetr/issues/20) figure B.

So I want to show gene SPP1, IL6, CTGF, IL24, MMP9, CXCL12, MMP1, and MMP2 in the plot shown here https://github.com/saeyslab/nichenetr/blob/master/vignettes/circos.md
using an additional layer(track).
So would please show few codes or a way to go?

Best,
Amare

**Comment by browaeysrobin** [comment]
Dear @adesalegn 

I don't have a code-based solution for this, so I can't provide you with code.
Please see my response to the open issue #20.
Therefore, I will close this issue.
