### ISSUE TITLE
Using NicheNet with MAGIC imputed data 

### ISSUE THREAD

**Issue by BiostormSilver** [saeyslab/nichenetr#97]
Hi,

Do you know whether using NicheNet with an data matrix imputed with MAGIC is an appropriate analysis to perform. MAGIC is designed to remove noise from the data and restore it's underlying structure, which in theory restores the data to what it'd look like if all the RNA from each cell was captured during sequencing. Therefore, performing NicheNet analysis on this restored data may allow better determination of the top-ligands and their downstream affects.

I'm asking here before using the analysis on imputed data to check whether of any assumptions used by the analyses within NicheNet that may be violated by this imputation.

**Comment by browaeysrobin** [comment]
Hi @BiostormSilver 

Unfortunately, I am not really familiar with MAGIC-imputed data. 
But I can tell what would be the most important things to consider:
* Calculation of NicheNet ligand activities: need to have a geneset of interest --> typically from DE analysis --> DE analysis on MAGIC-imputed data should be trustworthy - if not, I would suggest not using MAGIC-imputed data
* Definition of expressed ligands, receptors, and background genes: possible you might need to define your own function to define whether a gene is expressed in a certain cell type or not given MAGIC-imputed data.

**Comment by BiostormSilver** [comment]
Thanks for the quick reply, 

Considering the first point, it has been reported that MAGIC produces binomial distributed data that could violate distribution assumptions in DE tests, so it may not be trustworthy. However, I'm not sure how strong an affect the differences in distribution have on these tests. 

For the second point, it would need it own definition of whether a gene is expressed as there are pretty much no 0 count cells after imputation, although the cutoff for genes expressed could always be used before imputation so that may not be a problem. 

I imagine this just means that the validity of the results would be uncertain, so the results should be checked in some way. 

Thank you for your input.
