### ISSUE TITLE
Can I use a pre-determined target gene of interest to do the nichenet analysis?

### ISSUE THREAD

**Issue by lmilichUCSD** [saeyslab/nichenetr#99]
Hello, I am trying to determine the ligands, receptors, and downstream targets involved in turning on the expression of a specific transcription factor. Is there a way that I can use NicheNet to specify a target gene and then build the network around that? For example, maybe in the step that determines the gene set of interest in the receiver cell?

**Comment by browaeysrobin** [comment]
Hi @lmilichUCSD 

If I understand your question correctly, you want to know the potential upstream ligands inducing the expression of a specific gene (in your case a certain TF), and through which receptor & intracellular signaling paths this could happen?

If this is the case, you could use NicheNet in following two ways (and I suggest trying both):

1. `extract_top_n_ligands`to get the ligands with highest regulatory potential scores for the gene of interest (will rank ligands based on "absolute, total amount of evidence" supporting this relation) --> give some/all of the most interesting ligands and your gene of interest as input to the singaling-path-vignette https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_target_signaling_path.md
2. use the gene of interest as only gene in the geneset of interest in the ligand activity procedure (basic vignettes), with all the genes in the ligand-target matrix as background (more focus on "relative" amount of evidence) --> give some/all of the most interesting ligands and your gene of interest as input to the singaling-path-vignette
